Repository woowacourse-teams/2022-levellog, pull requests merged in 2022-08, with the labels that each got.

#169 refactor: 컨벤션 & 타입 리팩터링
  frontend/.webpack/webpack.common.js
  frontend/src/ModalPortal.tsx
  frontend/src/apis/feedback.ts
  frontend/src/apis/levellog.ts
  frontend/src/apis/login.ts
  frontend/src/apis/teams.ts
  frontend/src/components/@commons/Button.tsx
  frontend/src/components/@commons/ContentHeader.tsx
  frontend/src/components/@commons/Image.tsx
  frontend/src/components/@commons/Input.tsx
  frontend/src/components/@commons/Label.tsx
  frontend/src/components/@commons/Style.tsx
  frontend/src/components/Footer.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/ProfileDropdown.tsx
  frontend/src/components/feedbacks/Feedback.tsx
  frontend/src/components/feedbacks/FeedbackForm.tsx
  frontend/src/components/levellogs/LevellogForm.tsx
  frontend/src/components/levellogs/LevellogReport.tsx
  frontend/src/components/levellogs/LevellogViewModal.stories.tsx
  frontend/src/components/levellogs/LevellogViewModal.tsx
  frontend/src/components/teams/InterviewTeam.stories.tsx
  frontend/src/components/teams/InterviewTeam.tsx
  frontend/src/components/teams/Interviewer.stories.tsx
  frontend/src/components/teams/Interviewer.tsx
  frontend/src/constants/constants.ts
  frontend/src/hooks/useAuth.ts
  frontend/src/hooks/useFeedback.ts
  frontend/src/hooks/useLevellog.ts
  frontend/src/hooks/useLevellogModal.ts
  frontend/src/hooks/useTeams.ts
  frontend/src/index.tsx
  frontend/src/mocks/handler.ts
  frontend/src/pages/Login.tsx
  frontend/src/pages/feedback/FeedbackAdd.tsx
  frontend/src/pages/feedback/FeedbackList.tsx
  frontend/src/pages/levellogs/LevellogAdd.tsx
  frontend/src/pages/levellogs/LevellogEdit.tsx
  frontend/src/pages/teams/InterviewDetail.tsx
  frontend/src/pages/teams/InterviewTeams.tsx
  frontend/src/routes/Auth.tsx
  frontend/src/types/feedback.ts
  frontend/src/types/index.ts
  frontend/src/types/levellog.ts
  frontend/src/types/login.ts
  frontend/src/types/team.ts
  frontend/tsconfig.json
Labels: 🧑🏻‍💻 프론트엔드, 🛠 리팩터링

#170 fix: 팀 조회 API 변경에 대응한다.
  frontend/src/components/levellogs/LevellogViewModal.tsx
  frontend/src/components/teams/InterviewTeam.tsx
  frontend/src/components/teams/Interviewer.tsx
  frontend/src/mocks/handler.ts
  frontend/src/mocks/mockData.ts
  frontend/src/pages/teams/InterviewDetail.tsx
  frontend/src/types/team.ts
Labels: 🐛 버그, 🧑🏻‍💻 프론트엔드, Team

#175 fix: 팀 생성 시 중복된 참가자 예외 처리 로직 추가
  backend/src/docs/asciidoc/team.adoc
  backend/src/main/java/com/woowacourse/levellog/team/application/TeamService.java
  backend/src/main/java/com/woowacourse/levellog/team/exception/DuplicateParticipantsException.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/FeedbackAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/MyInfoAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/TeamServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/TeamControllerTest.java
Labels: 🐛 버그, 👩🏻‍💻 백엔드, Team

#173 fix: 팀 참가자 예외처리
  frontend/src/components/teams/Interviewer.tsx
  frontend/src/constants/constants.ts
  frontend/src/hooks/useTeams.ts
  frontend/src/pages/teams/InterviewDetail.tsx
Labels: 🐛 버그, 🧑🏻‍💻 프론트엔드

#167 feat: 인터뷰 질문 CRUD 구현
  backend/src/docs/asciidoc/index.adoc
  backend/src/docs/asciidoc/interviewquestion.adoc
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/application/InterviewQuestionService.java
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/domain/InterviewQuestion.java
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/domain/InterviewQuestionRepository.java
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/dto/InterviewQuestionDetailDto.java
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/dto/InterviewQuestionDto.java
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/dto/InterviewQuestionsDto.java
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/exception/InterviewQuestionNotFoundException.java
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/presentation/InterviewQuestionController.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/InterviewQuestionAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/FeedbackServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/InterviewQuestionServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/ServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/InterviewQuestionRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/InterviewQuestionTest.java
  backend/src/test/java/com/woowacourse/levellog/fixture/RestAssuredResponse.java
  backend/src/test/java/com/woowacourse/levellog/presentation/ControllerTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/InterviewQuestionControllerTest.java
Labels: 🌟 기능, 👩🏻‍💻 백엔드, InterviewQuestion

#171 feat: 인터뷰 역할 관련 기능을 추가한다.
  backend/src/docs/asciidoc/index.adoc
  backend/src/docs/asciidoc/team.adoc
  backend/src/main/java/com/woowacourse/levellog/authentication/config/LoginMemberResolver.java
  backend/src/main/java/com/woowacourse/levellog/common/domain/BaseEntity.java
  backend/src/main/java/com/woowacourse/levellog/team/application/TeamService.java
  backend/src/main/java/com/woowacourse/levellog/team/domain/InterviewRole.java
  backend/src/main/java/com/woowacourse/levellog/team/domain/Participants.java
  backend/src/main/java/com/woowacourse/levellog/team/domain/Team.java
  backend/src/main/java/com/woowacourse/levellog/team/dto/InterviewRoleDto.java
  backend/src/main/java/com/woowacourse/levellog/team/dto/TeamAndRoleDto.java
  backend/src/main/java/com/woowacourse/levellog/team/dto/TeamCreateDto.java
  backend/src/main/java/com/woowacourse/levellog/team/exception/ParticipantNotFoundException.java
  backend/src/main/java/com/woowacourse/levellog/team/presentation/TeamController.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/AcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/InterviewQuestionAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/LevellogAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/TeamAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/FeedbackServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/InterviewQuestionServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/LevellogServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/TeamServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/common/domain/MockEntityFactory.java
  backend/src/test/java/com/woowacourse/levellog/domain/FeedbackRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/FeedbackTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/InterviewQuestionRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/InterviewQuestionTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/LevellogRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/LevellogTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/ParticipantRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/TeamTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/TeamControllerTest.java
  backend/src/test/java/com/woowacourse/levellog/team/domain/ParticipantsTest.java
Labels: 🌟 기능, 👩🏻‍💻 백엔드, Team

#179 feat: 편한 글쓰기를 지원한다.
  frontend/package.json
  frontend/src/components/@commons/UiEditor.stories.tsx
  frontend/src/components/@commons/UiEditor.tsx
  frontend/src/components/@commons/UiViewer.stories.tsx
  frontend/src/components/@commons/UiViewer.tsx
  frontend/src/components/feedbacks/Feedback.tsx
  frontend/src/components/feedbacks/FeedbackFormat.tsx
  frontend/src/components/levellogs/LevellogReport.tsx
  frontend/src/components/levellogs/LevellogViewModal.tsx
  frontend/src/hooks/useFeedback.ts
  frontend/src/hooks/useLevellog.ts
  frontend/src/hooks/useLevellogModal.ts
  frontend/src/pages/feedback/FeedbackAdd.tsx
  frontend/src/pages/levellogs/LevellogAdd.tsx
  frontend/src/pages/levellogs/LevellogEdit.tsx
Labels: 🌟 기능, 🧑🏻‍💻 프론트엔드

#185 fix: 속하지 않은 팀의 피드백 조회를 요청시 예외 발생
  backend/src/main/java/com/woowacourse/levellog/feedback/application/FeedbackService.java
  backend/src/main/java/com/woowacourse/levellog/feedback/presentation/FeedbackController.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/AcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/FeedbackAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/LevellogAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/FeedbackServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/FeedbackControllerTest.java
Labels: 🐛 버그, 👩🏻‍💻 백엔드, Feedback, 📚 테스트

#181 feat: 인터뷰 팀 생성을 구현한다
  frontend/docs/README.md
  frontend/src/App.tsx
  frontend/src/apis/member.ts
  frontend/src/apis/teams.ts
  frontend/src/components/@commons/Input.tsx
  frontend/src/components/Footer.tsx
  frontend/src/components/feedbacks/Feedback.tsx
  frontend/src/components/levellogs/LevellogViewModal.tsx
  frontend/src/components/teams/Interviewer.tsx
  frontend/src/components/teams/Member.tsx
  frontend/src/components/teams/Participants.tsx
  frontend/src/components/teams/TeamAddForm.tsx
  frontend/src/components/teams/TeamAddInput.tsx
  frontend/src/constants/constants.ts
  frontend/src/contexts/userContext.tsx
  frontend/src/hooks/useMember.ts
  frontend/src/hooks/useTeams.ts
  frontend/src/hooks/useUser.ts
  frontend/src/hooks/useUtil.ts
  frontend/src/pages/Login.tsx
  frontend/src/pages/teams/InterviewTeamAdd.tsx
  frontend/src/pages/teams/InterviewTeams.tsx
  frontend/src/routes/Routes.tsx
  frontend/src/styles/colorPalette.ts
  frontend/src/styles/sizeList.ts
  frontend/src/types/index.ts
  frontend/src/types/member.ts
  frontend/src/types/team.ts
Labels: 🌟 기능, 🧑🏻‍💻 프론트엔드, Team

#183 fix: 로그인이 필요한 페이지에서 두 번의 `alert`이 뜨는 버그 수정
  frontend/src/components/levellogs/LevellogViewModal.tsx
  frontend/src/routes/Auth.tsx
Labels: 🐛 버그, 🧑🏻‍💻 프론트엔드

#188 fix: 유효하지 않은 토큰 예외처리
  frontend/src/constants/constants.ts
  frontend/src/pages/Login.tsx
Labels: 🐛 버그, 🧑🏻‍💻 프론트엔드

#189 chore: frontend ci 추가
  .github/workflows/frontBuild.yml
Labels: ⚙️ 설정, 🧑🏻‍💻 프론트엔드

#177 feat: MyInfo API 추가
  backend/src/docs/asciidoc/myinfo.adoc
  backend/src/main/java/com/woowacourse/levellog/levellog/application/LevellogService.java
  backend/src/main/java/com/woowacourse/levellog/levellog/domain/LevellogRepository.java
  backend/src/main/java/com/woowacourse/levellog/levellog/dto/LevellogWithIdDto.java
  backend/src/main/java/com/woowacourse/levellog/levellog/dto/LevellogsDto.java
  backend/src/main/java/com/woowacourse/levellog/member/presentation/MyInfoController.java
  backend/src/main/java/com/woowacourse/levellog/team/application/TeamService.java
  backend/src/main/java/com/woowacourse/levellog/team/domain/ParticipantRepository.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/MyInfoAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/LevellogServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/TeamServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/LevellogRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/ParticipantRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/MyInfoControllerTest.java
Labels: 🌟 기능, 👩🏻‍💻 백엔드, MyInfo

#176 feat: 팀 종료 기능 구현
  backend/src/docs/asciidoc/team.adoc
  backend/src/main/java/com/woowacourse/levellog/team/application/TeamService.java
  backend/src/main/java/com/woowacourse/levellog/team/domain/Team.java
  backend/src/main/java/com/woowacourse/levellog/team/dto/ParticipantIdsDto.java
  backend/src/main/java/com/woowacourse/levellog/team/dto/TeamAndRoleDto.java
  backend/src/main/java/com/woowacourse/levellog/team/dto/TeamCreateDto.java
  backend/src/main/java/com/woowacourse/levellog/team/dto/TeamDto.java
  backend/src/main/java/com/woowacourse/levellog/team/exception/HostUnauthorizedException.java
  backend/src/main/java/com/woowacourse/levellog/team/exception/InterviewTimeException.java
  backend/src/main/java/com/woowacourse/levellog/team/presentation/TeamController.java
  backend/src/main/java/com/woowacourse/levellog/team/support/LocalTimeStandard.java
  backend/src/main/java/com/woowacourse/levellog/team/support/TimeStandard.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/AcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/TeamAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/ServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/TeamServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/config/FakeTimeStandard.java
  backend/src/test/java/com/woowacourse/levellog/config/TestConfig.java
  backend/src/test/java/com/woowacourse/levellog/domain/TeamTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/TeamControllerTest.java
Labels: 🌟 기능, 👩🏻‍💻 백엔드, Team

#191 fix: myinfo uri 변경
  frontend/src/apis/login.ts
Labels: 🧑🏻‍💻 프론트엔드

#168 feat: 사전 질문 CRUD 구현
  backend/src/docs/asciidoc/index.adoc
  backend/src/docs/asciidoc/prequestion.adoc
  backend/src/main/java/com/woowacourse/levellog/levellog/domain/Levellog.java
  backend/src/main/java/com/woowacourse/levellog/prequestion/application/PreQuestionService.java
  backend/src/main/java/com/woowacourse/levellog/prequestion/domain/PreQuestion.java
  backend/src/main/java/com/woowacourse/levellog/prequestion/domain/PreQuestionRepository.java
  backend/src/main/java/com/woowacourse/levellog/prequestion/dto/PreQuestionDto.java
  backend/src/main/java/com/woowacourse/levellog/prequestion/exception/InvalidPreQuestionException.java
  backend/src/main/java/com/woowacourse/levellog/prequestion/exception/PreQuestionNotFoundException.java
  backend/src/main/java/com/woowacourse/levellog/prequestion/presentation/PreQuestionController.java
  backend/src/main/java/com/woowacourse/levellog/team/application/TeamService.java
  backend/src/main/java/com/woowacourse/levellog/team/domain/Participants.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/PreQuestionAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/PreQuestionServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/ServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/FeedbackRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/PreQuestionRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/PreQuestionTest.java
  backend/src/test/java/com/woowacourse/levellog/fixture/RestAssuredResponse.java
  backend/src/test/java/com/woowacourse/levellog/presentation/ControllerTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/PreQuestionControllerTest.java
Labels: 🌟 기능, 👩🏻‍💻 백엔드, PreQuestion

#192 fix: yarn lock 추가
  .github/workflows/frontBuild.yml
  frontend/.gitignore
  frontend/yarn.lock
Labels: 🧑🏻‍💻 프론트엔드

#193 fix: api 문서 링크 수정
  backend/src/docs/asciidoc/index.adoc
Labels: 🐛 버그, 📝 문서, 👩🏻‍💻 백엔드

#194 fix: feedback api 문서 snippet 링크 수정
  backend/src/docs/asciidoc/feedback.adoc
Labels: 🐛 버그, 📝 문서, 👩🏻‍💻 백엔드, Feedback

#199 feat: 팀 목록, 상세 조회 시 참가여부 필드 추가
  backend/src/main/java/com/woowacourse/levellog/team/application/TeamService.java
  backend/src/main/java/com/woowacourse/levellog/team/domain/Participants.java
  backend/src/main/java/com/woowacourse/levellog/team/dto/TeamAndRoleDto.java
  backend/src/main/java/com/woowacourse/levellog/team/dto/TeamDto.java
  backend/src/main/java/com/woowacourse/levellog/team/presentation/TeamController.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/TeamAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/TeamServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/ParticipantsTest.java
Labels: 🌟 기능, 👩🏻‍💻 백엔드, Team

#198 feat: 특정 레벨로그에 내가 작성한 사전 질문 조회 기능
  backend/src/docs/asciidoc/prequestion.adoc
  backend/src/main/java/com/woowacourse/levellog/prequestion/application/PreQuestionService.java
  backend/src/main/java/com/woowacourse/levellog/prequestion/domain/PreQuestionRepository.java
  backend/src/main/java/com/woowacourse/levellog/prequestion/presentation/PreQuestionController.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/PreQuestionAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/PreQuestionServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/PreQuestionRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/ControllerTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/MyInfoControllerTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/PreQuestionControllerTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/TeamControllerTest.java
Labels: 🌟 기능, 👩🏻‍💻 백엔드, PreQuestion

#200 feat: 팀 수정,삭제를 구현한다.
  frontend/docs/README.md
  frontend/src/apis/teams.ts
  frontend/src/components/@commons/Button.tsx
  frontend/src/components/levellogs/LevellogReport.tsx
  frontend/src/components/levellogs/LevellogViewModal.tsx
  frontend/src/components/teams/TeamAddForm.tsx
  frontend/src/components/teams/TeamAddInput.tsx
  frontend/src/components/teams/TeamEditForm.tsx
  frontend/src/constants/constants.ts
  frontend/src/hooks/useFeedback.ts
  frontend/src/hooks/useLevellog.ts
  frontend/src/hooks/useMember.ts
  frontend/src/hooks/useTeams.ts
  frontend/src/pages/teams/InterviewDetail.tsx
  frontend/src/pages/teams/InterviewTeamAdd.tsx
  frontend/src/pages/teams/InterviewTeamEdit.tsx
  frontend/src/routes/Routes.tsx
  frontend/src/types/team.ts
Labels: 🌟 기능, 🧑🏻‍💻 프론트엔드, Team

#211 fix: route 수정
  frontend/src/components/levellogs/LevellogViewModal.tsx
Labels: 🐛 버그, 🧑🏻‍💻 프론트엔드

#213 fix: 사전 질문이 이미 등록되었을 때 사전 질문을 등록하는 경우 예외 처리 추가
  backend/src/docs/asciidoc/prequestion.adoc
  backend/src/main/java/com/woowacourse/levellog/prequestion/application/PreQuestionService.java
  backend/src/main/java/com/woowacourse/levellog/prequestion/domain/PreQuestionRepository.java
  backend/src/main/java/com/woowacourse/levellog/prequestion/dto/PreQuestionAlreadyExistException.java
  backend/src/test/java/com/woowacourse/levellog/application/PreQuestionServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/PreQuestionRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/PreQuestionControllerTest.java
Labels: 🐛 버그, 👩🏻‍💻 백엔드, PreQuestion

#218 fix: sprint3 QA 버그를 수정한다.
  frontend/src/components/levellogs/LevellogViewModal.tsx
  frontend/src/components/preQuestion/PreQuestionViewModal.tsx
  frontend/src/components/teams/Interviewer.tsx
  frontend/src/hooks/useLevellogModal.ts
  frontend/src/hooks/usePreQuestionModal.ts
  frontend/src/pages/teams/InterviewDetail.tsx
  frontend/src/styles/GlobalStyle.ts
Labels: 🐛 버그, 🧑🏻‍💻 프론트엔드

#223 test: e2e 테스트
  frontend/cypress.config.ts
  frontend/cypress/e2e/PageRoute.cy.ts
  frontend/cypress/support/commands.ts
  frontend/cypress/support/e2e.ts
  frontend/package.json
  frontend/src/hooks/useTeams.ts
  frontend/yarn.lock
Labels: ⚙️ 설정, 🧑🏻‍💻 프론트엔드, 📚 테스트

#230 feat: 역할 기능을 구현
  frontend/docs/README.md
  frontend/src/apis/role.ts
  frontend/src/assets/images/group.png
  frontend/src/assets/images/mic.png
  frontend/src/components/@commons/Role.tsx
  frontend/src/components/teams/Interviewer.tsx
  frontend/src/hooks/useMember.ts
  frontend/src/hooks/usePreQuestion.ts
  frontend/src/hooks/useRole.ts
  frontend/src/hooks/useTeams.ts
  frontend/src/hooks/useUser.ts
  frontend/src/pages/Login.tsx
  frontend/src/pages/feedback/FeedbackAdd.tsx
  frontend/src/pages/feedback/FeedbackList.tsx
  frontend/src/pages/preQuestion/PreQuestionAdd.tsx
  frontend/src/pages/preQuestion/PreQuestionEdit.tsx
  frontend/src/pages/teams/InterviewDetail.tsx
  frontend/src/pages/teams/InterviewTeams.tsx
  frontend/src/routes/Routes.tsx
  frontend/src/styles/colorPalette.ts
  frontend/src/types/role.ts
  frontend/src/types/team.ts
Labels: 🐛 버그, 🌟 기능, 🧑🏻‍💻 프론트엔드, 🛠 리팩터링, Team

#231 fix: sprint3 버그 수정
  frontend/package-lock.json
  frontend/src/components/ProfileDropdown.tsx
  frontend/src/hooks/useLevellog.ts
  frontend/src/hooks/useLevellogModal.ts
  frontend/src/hooks/useTeams.ts
  frontend/src/pages/teams/InterviewDetail.tsx
  frontend/yarn.lock
Labels: 🐛 버그, 🧑🏻‍💻 프론트엔드

#232 fix: 팀 생성 성공시 라우팅 변경
  frontend/src/hooks/useTeams.ts
  frontend/src/pages/feedback/FeedbackAdd.tsx
Labels: 🐛 버그, 🧑🏻‍💻 프론트엔드

#233 release: v1.1.1
  frontend/docs/README.md
  frontend/package-lock.json
  frontend/src/apis/role.ts
  frontend/src/assets/images/group.png
  frontend/src/assets/images/mic.png
  frontend/src/components/@commons/Role.tsx
  frontend/src/components/ProfileDropdown.tsx
  frontend/src/components/teams/Interviewer.tsx
  frontend/src/hooks/useLevellog.ts
  frontend/src/hooks/useLevellogModal.ts
  frontend/src/hooks/useMember.ts
  frontend/src/hooks/usePreQuestion.ts
  frontend/src/hooks/useRole.ts
  frontend/src/hooks/useTeams.ts
  frontend/src/hooks/useUser.ts
  frontend/src/pages/Login.tsx
  frontend/src/pages/feedback/FeedbackAdd.tsx
  frontend/src/pages/feedback/FeedbackList.tsx
  frontend/src/pages/preQuestion/PreQuestionAdd.tsx
  frontend/src/pages/preQuestion/PreQuestionEdit.tsx
  frontend/src/pages/teams/InterviewDetail.tsx
  frontend/src/pages/teams/InterviewTeams.tsx
  frontend/src/routes/Routes.tsx
  frontend/src/styles/colorPalette.ts
  frontend/src/types/role.ts
  frontend/src/types/team.ts
  frontend/yarn.lock
Labels: 🐛 버그

#250 feat: host가 팀의 인터뷰를 종료할 수 있도록 한다.
  frontend/docs/README.md
  frontend/src/apis/teams.ts
  frontend/src/components/teams/InterviewTeam.tsx
  frontend/src/constants/constants.ts
  frontend/src/hooks/useTeams.ts
  frontend/src/pages/teams/InterviewDetail.tsx
Labels: 🌟 기능, 🧑🏻‍💻 프론트엔드, Team

#251 feat: 사전에 닉네임을 설정한 멤버를 저장 시, 멤버의 닉네임을 미리 저장한 닉네임으로 변경하여 저장하도록 수정한다.
  backend/src/docs/asciidoc/myinfo.adoc
  backend/src/main/java/com/woowacourse/levellog/member/application/MemberService.java
  backend/src/main/java/com/woowacourse/levellog/member/domain/NicknameMapping.java
  backend/src/main/java/com/woowacourse/levellog/member/domain/NicknameMappingRepository.java
  backend/src/test/java/com/woowacourse/levellog/application/MemberServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/ServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/MemberTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/NicknameMappingRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/MyInfoControllerTest.java
Labels: 🌟 기능, 👩🏻‍💻 백엔드, Member

#259 refactor: 인수테스트에서 사용중인 `@DirtiesContext` 제거
  backend/src/test/java/com/woowacourse/levellog/acceptance/AcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/config/DatabaseCleaner.java
Labels: 👩🏻‍💻 백엔드, 🛠 리팩터링

#253 feat: 레벨로그 상세 조회 시 body에 작성자의 정보도 제공하도록 수정한다.
  backend/src/main/java/com/woowacourse/levellog/levellog/application/LevellogService.java
  backend/src/main/java/com/woowacourse/levellog/levellog/dto/LevellogDto.java
  backend/src/main/java/com/woowacourse/levellog/levellog/dto/LevellogWriteDto.java
  backend/src/main/java/com/woowacourse/levellog/levellog/presentation/LevellogController.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/FeedbackAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/InterviewQuestionAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/LevellogAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/MyInfoAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/PreQuestionAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/LevellogServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/LevellogControllerTest.java
Labels: 🌟 기능, 👩🏻‍💻 백엔드, Levellog

#252 feat: 피드백 생성, 수정 시 바뀐 정책 적용
  backend/src/docs/asciidoc/feedback.adoc
  backend/src/main/java/com/woowacourse/levellog/feedback/application/FeedbackService.java
  backend/src/main/java/com/woowacourse/levellog/feedback/domain/Feedback.java
  backend/src/main/java/com/woowacourse/levellog/feedback/exception/InvalidFeedbackException.java
  backend/src/main/java/com/woowacourse/levellog/feedback/presentation/FeedbackController.java
  backend/src/main/java/com/woowacourse/levellog/team/domain/Team.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/FeedbackAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/FeedbackServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/TeamTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/FeedbackControllerTest.java
Labels: 👩🏻‍💻 백엔드, Feedback

#254 feat: 레벨로그 생성, 수정 시 바뀐 정책 적용
  backend/src/docs/asciidoc/levellog.adoc
  backend/src/main/java/com/woowacourse/levellog/levellog/application/LevellogService.java
  backend/src/main/java/com/woowacourse/levellog/levellog/presentation/LevellogController.java
  backend/src/main/java/com/woowacourse/levellog/team/domain/Team.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/AcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/FeedbackAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/InterviewQuestionAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/LevellogAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/MyInfoAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/PreQuestionAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/TeamAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/LevellogServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/ServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/config/FakeTimeStandard.java
  backend/src/test/java/com/woowacourse/levellog/domain/LevellogTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/TeamTest.java
  backend/src/test/java/com/woowacourse/levellog/fixture/TimeFixture.java
  backend/src/test/java/com/woowacourse/levellog/presentation/InterviewQuestionControllerTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/LevellogControllerTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/MyInfoControllerTest.java
Labels: 🌟 기능, 👩🏻‍💻 백엔드, Levellog

#257 feat: 인터뷰 질문 생성, 수정, 삭제 시 바뀐 정책 적용
  backend/src/docs/asciidoc/auth.adoc
  backend/src/docs/asciidoc/feedback.adoc
  backend/src/docs/asciidoc/interviewquestion.adoc
  backend/src/docs/asciidoc/myinfo.adoc
  backend/src/docs/asciidoc/prequestion.adoc
  backend/src/main/java/com/woowacourse/levellog/common/exception/LevellogException.java
  backend/src/main/java/com/woowacourse/levellog/feedback/application/FeedbackService.java
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/application/InterviewQuestionService.java
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/domain/InterviewQuestion.java
  backend/src/main/java/com/woowacourse/levellog/levellog/application/LevellogService.java
  backend/src/main/java/com/woowacourse/levellog/team/domain/Team.java
  backend/src/main/java/com/woowacourse/levellog/team/exception/InterviewTimeException.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/InterviewQuestionAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/FeedbackServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/InterviewQuestionServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/PreQuestionServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/FeedbackRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/FeedbackTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/InterviewQuestionRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/InterviewQuestionTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/LevellogRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/MemberRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/ParticipantRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/ParticipantsTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/PreQuestionRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/PreQuestionTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/RepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/TeamTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/InterviewQuestionControllerTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/TeamControllerTest.java
Labels: 🌟 기능, 👩🏻‍💻 백엔드, InterviewQuestion

#258 refactor: 픽스처를 활용해서 repository 테스트 개선
  backend/src/test/java/com/woowacourse/levellog/domain/FeedbackRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/InterviewQuestionRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/LevellogRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/MemberRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/ParticipantRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/PreQuestionRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/RepositoryTest.java
Labels: 👩🏻‍💻 백엔드, 🛠 리팩터링

#260 feat: 팀 수정, 삭제 시 바뀐 정책 적용
  backend/src/docs/asciidoc/team.adoc
  backend/src/main/java/com/woowacourse/levellog/team/application/TeamService.java
  backend/src/main/java/com/woowacourse/levellog/team/domain/Team.java
  backend/src/main/java/com/woowacourse/levellog/team/domain/TeamStatus.java
  backend/src/main/java/com/woowacourse/levellog/team/dto/TeamAndRoleDto.java
  backend/src/main/java/com/woowacourse/levellog/team/dto/TeamDto.java
  backend/src/main/java/com/woowacourse/levellog/team/dto/TeamUpdateDto.java
  backend/src/main/java/com/woowacourse/levellog/team/dto/TeamWriteDto.java
  backend/src/main/java/com/woowacourse/levellog/team/presentation/TeamController.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/AcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/InterviewQuestionAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/LevellogAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/MyInfoAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/PreQuestionAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/TeamAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/ServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/TeamServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/TeamTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/TeamControllerTest.java
Labels: 🌟 기능, 👩🏻‍💻 백엔드, 🛠 리팩터링, Team

#273 refactor: 픽스처를 활용해서 ServiceTest 개선
  backend/src/test/java/com/woowacourse/levellog/application/FeedbackServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/InterviewQuestionServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/LevellogServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/MemberServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/OAuthServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/PreQuestionServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/ServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/TeamServiceTest.java
Labels: 👩🏻‍💻 백엔드, 🛠 리팩터링, 📚 테스트

#272 fix: Team API 문서 수정
  backend/src/docs/asciidoc/team.adoc
  backend/src/test/java/com/woowacourse/levellog/presentation/TeamControllerTest.java
Labels: 🐛 버그, 📝 문서, 👩🏻‍💻 백엔드, Team

#269 feat: 인터뷰 질문 crud 구현
  frontend/src/apis/interviewQuestion.ts
  frontend/src/components/@commons/Button.tsx
  frontend/src/components/@commons/ToolTip.stories.tsx
  frontend/src/components/@commons/ToolTip.tsx
  frontend/src/components/feedbacks/FeedbackFormat.tsx
  frontend/src/components/interviewQuestion/InterviewQuestion.tsx
  frontend/src/components/interviewQuestion/InterviewQuestionContent.tsx
  frontend/src/components/levellogs/LevellogReport.tsx
  frontend/src/components/preQuestion/PreQuestionViewModal.tsx
  frontend/src/components/teams/Interviewer.tsx
  frontend/src/constants/constants.ts
  frontend/src/hooks/useInterviewQuestion.ts
  frontend/src/hooks/useInterviewQuestionEdit.ts
  frontend/src/hooks/useRole.ts
  frontend/src/hooks/useScrollDown.ts
  frontend/src/pages/feedback/FeedbackAdd.tsx
  frontend/src/pages/feedback/Feedbacks.tsx
  frontend/src/pages/interviewQuestion/InterviewQuestions.tsx
  frontend/src/routes/Auth.tsx
  frontend/src/routes/Routes.tsx
  frontend/src/types/interviewQuestion.ts
  frontend/src/types/role.ts
Labels: 🌟 기능, 🧑🏻‍💻 프론트엔드

#275 feat: 인증&인가 구현
  frontend/docs/README.md
  frontend/src/apis/feedback.ts
  frontend/src/apis/levellog.ts
  frontend/src/components/ProfileDropdown.stories.tsx
  frontend/src/components/feedbacks/Feedback.tsx
  frontend/src/components/feedbacks/FeedbackForm.tsx
  frontend/src/components/levellogs/LevellogViewModal.stories.tsx
  frontend/src/components/levellogs/LevellogViewModal.tsx
  frontend/src/components/teams/InterviewTeam.stories.tsx
  frontend/src/components/teams/InterviewTeam.tsx
  frontend/src/components/teams/Interviewer.stories.tsx
  frontend/src/components/teams/Interviewer.tsx
  frontend/src/components/teams/Member.tsx
  frontend/src/components/teams/Participants.tsx
  frontend/src/components/teams/TeamEditForm.tsx
  frontend/src/components/teams/TeamForm.tsx
  frontend/src/components/teams/TeamFormInput.tsx
  frontend/src/constants/constants.ts
  frontend/src/contexts/teamContext.tsx
  frontend/src/contexts/userContext.tsx
  frontend/src/hooks/useAuth.ts
  frontend/src/hooks/useFeedback.ts
  frontend/src/hooks/useLevellog.ts
  frontend/src/hooks/useLevellogModal.ts
  frontend/src/hooks/useMember.ts
  frontend/src/hooks/useRole.ts
  frontend/src/hooks/useTeam.ts
  frontend/src/hooks/useTeams.ts
  frontend/src/hooks/useUtil.ts
  frontend/src/index.tsx
  frontend/src/mocks/browser.ts
  frontend/src/mocks/handler.ts
  frontend/src/mocks/mockData.ts
  frontend/src/pages/Login.tsx
  frontend/src/pages/feedback/FeedbackAdd.tsx
  frontend/src/pages/feedback/FeedbackEdit.tsx
  frontend/src/pages/feedback/Feedbacks.tsx
  frontend/src/pages/preQuestion/PreQuestionAdd.tsx
  frontend/src/pages/preQuestion/PreQuestionEdit.tsx
  frontend/src/pages/status/Error.tsx
  frontend/src/pages/status/Loading.tsx
  frontend/src/pages/status/NotFound.tsx
  frontend/src/pages/teams/InterviewDetail.tsx
  frontend/src/pages/teams/InterviewTeamAdd.tsx
  frontend/src/pages/teams/InterviewTeamEdit.tsx
  frontend/src/pages/teams/InterviewTeams.tsx
  frontend/src/routes/Auth.tsx
  frontend/src/routes/AuthLogin.tsx
  frontend/src/routes/Routes.tsx
  frontend/src/routes/TeamStatus.tsx
  frontend/src/types/team.ts
Labels: 🧑🏻‍💻 프론트엔드

#279 hotfix: CI 스크립트에서 labeled 설정 제거
  .github/workflows/frontBuild.yml
  .github/workflows/main.yml
Labels: ⚙️ 설정

#276 refactor: 컨트롤러 테스트 리팩토링
  backend/src/docs/asciidoc/interviewquestion.adoc
  backend/src/test/java/com/woowacourse/levellog/presentation/ControllerTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/FeedbackControllerTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/InterviewQuestionControllerTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/LevellogControllerTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/MyInfoControllerTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/OAuthControllerTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/PreQuestionControllerTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/TeamControllerTest.java
Labels: 👩🏻‍💻 백엔드, 🛠 리팩터링, 📚 테스트

#293 refactor: 인수테스트 리팩토링
  backend/src/main/java/com/woowacourse/levellog/feedback/dto/FeedbackWriteDto.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/AcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/FeedbackAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/InterviewQuestionAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/LevellogAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/MyInfoAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/PreQuestionAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/TeamAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/FeedbackServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/fixture/MemberFixture.java
  backend/src/test/java/com/woowacourse/levellog/fixture/RestAssuredResponse.java
  backend/src/test/java/com/woowacourse/levellog/presentation/FeedbackControllerTest.java
Labels: 👩🏻‍💻 백엔드, 🛠 리팩터링

#288 feat: 특정 레벨로그에 작성된 인터뷰 질문 목록 조회
  backend/src/docs/asciidoc/interviewquestion.adoc
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/application/InterviewQuestionService.java
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/domain/InterviewQuestion.java
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/domain/InterviewQuestionRepository.java
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/dto/InterviewQuestionContentDto.java
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/dto/InterviewQuestionContentsDto.java
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/dto/InterviewQuestionDto.java
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/dto/InterviewQuestionWriteDto.java
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/dto/InterviewQuestionsDto.java
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/presentation/InterviewQuestionController.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/AcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/InterviewQuestionAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/InterviewQuestionServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/ServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/InterviewQuestionRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/RepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/InterviewQuestionControllerTest.java
Labels: 🌟 기능, 👩🏻‍💻 백엔드, InterviewQuestion

#298 feat: 참가자 수정 기능 구현
  backend/src/main/java/com/woowacourse/levellog/team/application/TeamService.java
  backend/src/test/java/com/woowacourse/levellog/application/TeamServiceTest.java
Labels: 🌟 기능, 👩🏻‍💻 백엔드, Team

#289 chore: Jacoco 라이브러리 적용
  backend/build.gradle
  backend/lombok.config
Labels: 👩🏻‍💻 백엔드, ⚙️ 설정, 📚 테스트

#300 refactor: 테스트 코드 네이밍 컨벤션 수정
  backend/src/docs/asciidoc/auth.adoc
  backend/src/docs/asciidoc/feedback.adoc
  backend/src/docs/asciidoc/interviewquestion.adoc
  backend/src/docs/asciidoc/levellog.adoc
  backend/src/docs/asciidoc/myinfo.adoc
  backend/src/docs/asciidoc/prequestion.adoc
  backend/src/docs/asciidoc/team.adoc
  backend/src/test/java/com/woowacourse/levellog/acceptance/MyInfoAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/TeamAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/FeedbackServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/InterviewQuestionServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/LevellogServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/MemberServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/OAuthServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/PreQuestionServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/TeamServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/FeedbackTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/InterviewQuestionTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/LevellogRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/LevellogTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/MemberTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/ParticipantsTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/PreQuestionRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/PreQuestionTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/TeamTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/FeedbackControllerTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/InterviewQuestionControllerTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/LevellogControllerTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/MyInfoControllerTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/OAuthControllerTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/PreQuestionControllerTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/TeamControllerTest.java
  backend/src/test/java/com/woowacourse/levellog/support/JwtTokenProviderTest.java
Labels: 👩🏻‍💻 백엔드, 🛠 리팩터링, 📚 테스트

#297 chore: 로그 개선
  backend/src/main/java/com/woowacourse/levellog/common/aspect/LogAspect.java
  backend/src/main/java/com/woowacourse/levellog/common/config/LogInterceptor.java
  backend/src/main/java/com/woowacourse/levellog/common/config/WebConfig.java
  backend/src/main/java/com/woowacourse/levellog/common/presentation/ControllerAdvice.java
  backend/src/main/resources/appender/console/console-appender.xml
  backend/src/main/resources/appender/console/parameter-appender.xml
  backend/src/main/resources/appender/console/query-appender.xml
  backend/src/main/resources/appender/file/error-appender.xml
  backend/src/main/resources/appender/file/info-appender.xml
  backend/src/main/resources/appender/file/warn-appender.xml
  backend/src/main/resources/appender/property.xml
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-test.yml
  backend/src/main/resources/application.yml
  backend/src/main/resources/logback-spring.xml
  backend/src/test/java/com/woowacourse/levellog/domain/NicknameMappingRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/RepositoryTest.java
Labels: 👩🏻‍💻 백엔드, ⚙️ 설정

#290 fix: 로그인 토큰과 관련한 버그 수정
  frontend/src/apis/utils.ts
  frontend/src/constants/constants.ts
  frontend/src/hooks/useAuth.ts
  frontend/src/hooks/useFeedback.ts
  frontend/src/hooks/useInterviewQuestion.ts
  frontend/src/hooks/useLevellog.ts
  frontend/src/hooks/useLevellogModal.ts
  frontend/src/hooks/usePreQuestion.ts
  frontend/src/hooks/useRole.ts
  frontend/src/hooks/useTeam.ts
  frontend/src/hooks/useTeams.ts
  frontend/src/hooks/useUser.ts
  frontend/src/pages/Login.tsx
Labels: 🐛 버그, 🧑🏻‍💻 프론트엔드, Auth

#291 feat: 사전질문추가 페이지 스타일 수정
  frontend/src/components/levellogs/LevellogReport.tsx
  frontend/src/pages/feedback/FeedbackAdd.tsx
  frontend/src/pages/preQuestion/PreQuestionAdd.tsx
Labels: 🧑🏻‍💻 프론트엔드, PreQuestion

#301 feat: 레벨로그 API 변경으로 인한 수정
  frontend/src/apis/levellog.ts
  frontend/src/components/feedbacks/Feedback.tsx
  frontend/src/components/interviewQuestion/InterviewQuestionContent.tsx
  frontend/src/components/levellogs/LevellogReport.tsx
  frontend/src/components/levellogs/LevellogViewModal.tsx
  frontend/src/constants/constants.ts
  frontend/src/hooks/useFeedback.ts
  frontend/src/hooks/useFeedbackAddPage.ts
  frontend/src/hooks/useLevellog.ts
  frontend/src/hooks/useLevellogModal.ts
  frontend/src/hooks/useRole.ts
  frontend/src/pages/feedback/FeedbackAdd.tsx
  frontend/src/pages/preQuestion/PreQuestionAdd.tsx
  frontend/src/pages/preQuestion/PreQuestionEdit.tsx
  frontend/src/pages/teams/InterviewDetail.tsx
  frontend/src/types/levellog.ts
Labels: 🌟 기능, 🧑🏻‍💻 프론트엔드

#295 fix: 팀 수정에 관한 버그, 다중역할에 관한 버그를 해결한다.
  frontend/src/assets/images/handshake.png
  frontend/src/components/@commons/Role.tsx
  frontend/src/components/feedbacks/Feedback.tsx
  frontend/src/components/levellogs/LevellogViewModal.tsx
  frontend/src/components/teams/Interviewer.tsx
  frontend/src/constants/constants.ts
  frontend/src/hooks/useAuth.ts
  frontend/src/hooks/useTeam.ts
  frontend/src/pages/feedback/Feedbacks.tsx
  frontend/src/routes/Routes.tsx
  frontend/src/routes/TeamStatus.tsx
Labels: 🐛 버그, 🌟 기능, 🧑🏻‍💻 프론트엔드

#305 feat: 피드백 페이지에서 사전질문 조회
  frontend/src/components/WriterDocument.tsx
  frontend/src/constants/constants.ts
  frontend/src/hooks/useContentTag.ts
  frontend/src/hooks/useFeedbackAddPage.ts
  frontend/src/hooks/useRole.ts
  frontend/src/pages/feedback/FeedbackAdd.tsx
Labels: 🌟 기능, 🧑🏻‍💻 프론트엔드, Feedback

#312 feat: 디자인 변경 소스 추가
  frontend/src/assets/fonts/NanumSquare_ac.woff
  frontend/src/assets/fonts/noto-sans-kr-v27-latin-regular.woff
  frontend/src/assets/images/angle-left-free-icon-font.webp
  frontend/src/assets/images/angle-right-free-icon-font.webp
  frontend/src/assets/images/check.webp
  frontend/src/assets/images/close.webp
  frontend/src/assets/images/delete-button.webp
  frontend/src/assets/images/free-icon-cone-7564055.webp
  frontend/src/assets/images/free-icon-font-add-3914208 (1).webp
  frontend/src/assets/images/free-icon-font-edit-3917361.webp
  frontend/src/assets/images/free-icon-font-interface-3917628.webp
  frontend/src/assets/images/free-icon-font-list-check-391439.webp
  frontend/src/assets/images/free-icon-font-x-7720332.webp
  frontend/src/assets/images/free-icon-handwriting-6604551.webp
  frontend/src/assets/images/free-icon-placeholder-149060 (3).webp
  frontend/src/assets/images/group.webp
  frontend/src/assets/images/handshake.webp
  frontend/src/assets/images/levellogLogoLeft.png
  frontend/src/assets/images/levellogNewLogo.png
  frontend/src/assets/images/mic.webp
  frontend/src/assets/images/plus-sign.webp
  frontend/src/assets/images/premium-icon-version-5558289.webp
  frontend/src/assets/images/question.webp
  frontend/src/components/@commons/Button.tsx
  frontend/src/styles/GlobalStyle.ts
  frontend/src/styles/colorPalette.ts
  frontend/src/styles/theme.ts
Labels: 🧑🏻‍💻 프론트엔드

#316 feat: 피드백 상세 조회 기능을 구현
  backend/src/docs/asciidoc/feedback.adoc
  backend/src/main/java/com/woowacourse/levellog/feedback/application/FeedbackService.java
  backend/src/main/java/com/woowacourse/levellog/feedback/domain/Feedback.java
  backend/src/main/java/com/woowacourse/levellog/feedback/presentation/FeedbackController.java
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/application/InterviewQuestionService.java
  backend/src/main/java/com/woowacourse/levellog/levellog/exception/InvalidLevellogException.java
  backend/src/main/java/com/woowacourse/levellog/prequestion/domain/PreQuestion.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/FeedbackAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/FeedbackServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/PreQuestionServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/FeedbackControllerTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/PreQuestionControllerTest.java
Labels: 🌟 기능, 👩🏻‍💻 백엔드, Feedback, 🚨 빨리!

#324 fix: 나에게 작성하는 인터뷰 질문 방어로직 작성
  backend/src/docs/asciidoc/interviewquestion.adoc
  backend/src/main/java/com/woowacourse/levellog/common/exception/LevellogException.java
  backend/src/main/java/com/woowacourse/levellog/common/support/DebugMessage.java
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/application/InterviewQuestionService.java
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/exception/InvalidInterviewQuestionException.java
  backend/src/main/java/com/woowacourse/levellog/levellog/domain/Levellog.java
  backend/src/test/java/com/woowacourse/levellog/application/InterviewQuestionServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/InterviewQuestionControllerTest.java
  backend/src/test/java/com/woowacourse/levellog/support/DebugMessageTest.java
  backend/src/test/java/com/woowacourse/levellog/support/JwtTokenProviderTest.java
Labels: 🐛 버그, 👩🏻‍💻 백엔드, InterviewQuestion

#319 feat: 레벨로그에 대한 전체 인터뷰 질문 조회를 구현
  frontend/src/apis/interviewQuestion.ts
  frontend/src/components/interviewQuestion/InterviewQuestion.tsx
  frontend/src/components/interviewQuestion/InterviewQuestionContent.tsx
  frontend/src/constants/util.ts
  frontend/src/hooks/useInterviewQuestion.ts
  frontend/src/hooks/useInterviewQuestionEdit.ts
  frontend/src/pages/interviewQuestion/InterviewQuestions.tsx
  frontend/src/types/interviewQuestion.ts
Labels: 🧑🏻‍💻 프론트엔드, InterviewQuestion

#323 feat: 피드백 조회 스타일 수정
  frontend/src/components/feedbacks/Feedback.tsx
  frontend/src/styles/GlobalStyle.ts
  frontend/src/types/feedback.ts
Labels: 🧑🏻‍💻 프론트엔드, Feedback

#335 feat: 상세 팀 조회 ( + 모달, vlog형태) 스타일 수정
  frontend/.webpack/webpack.common.js
  frontend/index.d.ts
  frontend/src/App.tsx
  frontend/src/components/@commons/Role.tsx
  frontend/src/components/levellogs/LevellogViewModal.tsx
  frontend/src/components/preQuestion/PreQuestionViewModal.tsx
  frontend/src/components/teams/Interviewer.tsx
  frontend/src/pages/teams/InterviewDetail.tsx
  frontend/src/styles/colorPalette.ts
Labels: 🧑🏻‍💻 프론트엔드, Team

#332 feat: 헤더,푸터,컨텐트헤더의 UI 변경을 반영
  frontend/src/App.tsx
  frontend/src/assets/images/angle-right-free-icon-font.webp
  frontend/src/assets/images/defaultProfile.png
  frontend/src/assets/images/free-icon-font-add-3914208 (1).webp
  frontend/src/assets/images/free-icon-font-edit-3917361.webp
  frontend/src/assets/images/free-icon-font-interface-3917628.webp
  frontend/src/assets/images/free-icon-font-list-check-391439.webp
  frontend/src/assets/images/free-icon-font-x-7720332.webp
  frontend/src/assets/images/free-icon-placeholder-149060 (3).webp
  frontend/src/assets/images/group.webp
  frontend/src/assets/images/hamburgerMenu.png
  frontend/src/assets/images/hamburgerMenu.webp
  frontend/src/assets/images/handshake.webp
  frontend/src/assets/images/levellogLogoLeft.png
  frontend/src/assets/images/levellogNewLogo.png
  frontend/src/components/@commons/ContentHeader.tsx
  frontend/src/components/@commons/FilterButton.tsx
  frontend/src/components/@commons/Image.tsx
  frontend/src/components/@commons/Style.tsx
  frontend/src/components/Footer.tsx
  frontend/src/components/ProfileDropdown.tsx
  frontend/src/components/header/Header.stories.tsx
  frontend/src/components/header/Header.tsx
  frontend/src/components/header/Profile.tsx
  frontend/src/components/header/ProfileDropdown.tsx
  frontend/src/hooks/useUser.ts
  frontend/src/pages/teams/InterviewTeams.tsx
  frontend/src/styles/GlobalStyle.ts
Labels: 🧑🏻‍💻 프론트엔드, 🛠 리팩터링

#339 fix: 주석 수정
  frontend/src/App.tsx
Labels: 🐛 버그, 🧑🏻‍💻 프론트엔드

#336 feat: 팀 조회,생성,수정페이지의 UI 변경을 반영
  frontend/src/App.tsx
  frontend/src/assets/images/add.png
  frontend/src/assets/images/check.png
  frontend/src/assets/images/check.webp
  frontend/src/assets/images/mic.webp
  frontend/src/assets/images/placeholder.png
  frontend/src/assets/images/plus-sign.webp
  frontend/src/components/@commons/ContentHeader.tsx
  frontend/src/components/@commons/Image.tsx
  frontend/src/components/Footer.tsx
  frontend/src/components/header/Header.tsx
  frontend/src/components/header/ProfileDropdown.tsx
  frontend/src/components/teams/InterviewTeam.tsx
  frontend/src/components/teams/Interviewer.tsx
  frontend/src/components/teams/Participants.tsx
  frontend/src/components/teams/TeamForm.tsx
  frontend/src/components/teams/TeamFormInput.tsx
  frontend/src/hooks/useTeam.ts
  frontend/src/pages/teams/InterviewTeamAdd.tsx
  frontend/src/pages/teams/InterviewTeamEdit.tsx
  frontend/src/pages/teams/InterviewTeams.tsx
  frontend/src/styles/GlobalStyle.ts
  frontend/src/styles/sizeList.ts
  frontend/src/types/index.ts
Labels: 🧑🏻‍💻 프론트엔드, 🛠 리팩터링, Team

#340 hotfix: 잘못된 머지파일 수정
  frontend/src/components/teams/Interviewer.tsx
  frontend/src/pages/teams/InterviewTeams.tsx
Labels: 🐛 버그, 🧑🏻‍💻 프론트엔드, 🚨 빨리!

#303 chore: 소나큐브 적용
  .github/workflows/main.yml
  backend/build.gradle
Labels: 🌟 기능, 👩🏻‍💻 백엔드, 🏭 인프라

#345 chore: github-script 버전 4로 업데이트
  .github/workflows/main.yml
Labels: 👩🏻‍💻 백엔드, 🏭 인프라

#342 feat: 예외처리 페이지 추가
  frontend/src/components/levellogs/LevellogViewModal.tsx
  frontend/src/components/preQuestion/PreQuestionViewModal.tsx
  frontend/src/components/teams/Interviewer.tsx
  frontend/src/constants/constants.ts
  frontend/src/hooks/useFeedbackAddPage.ts
  frontend/src/hooks/useLevellog.ts
  frontend/src/hooks/usePreQuestion.ts
  frontend/src/hooks/usePreQuestionModal.ts
  frontend/src/pages/feedback/Feedbacks.tsx
  frontend/src/pages/interviewQuestion/InterviewQuestions.tsx
  frontend/src/pages/levellogs/LevellogAdd.tsx
  frontend/src/pages/levellogs/LevellogEdit.tsx
  frontend/src/pages/preQuestion/PreQuestionAdd.tsx
  frontend/src/pages/preQuestion/PreQuestionEdit.tsx
  frontend/src/pages/status/EmptyFeedback.tsx
  frontend/src/pages/status/EmptyInterviewQuestion.tsx
  frontend/src/pages/status/Error.tsx
  frontend/src/pages/status/Loading.tsx
  frontend/src/pages/status/NotFound.tsx
  frontend/src/pages/status/index.tsx
  frontend/src/pages/teams/InterviewDetail.tsx
  frontend/src/pages/teams/InterviewTeamAdd.tsx
  frontend/src/routes/Auth.tsx
  frontend/src/routes/Routes.tsx
  frontend/src/styles/sizeList.ts
  frontend/src/types/index.ts
Labels: 🌟 기능, 🧑🏻‍💻 프론트엔드

#346 feat: 레벨로그, 사전질문, 피드백 (생성,수정) 페이지 UI 변경 반영
  frontend/src/components/@commons/BottomBar.tsx
  frontend/src/components/@commons/Button.tsx
  frontend/src/components/@commons/ContentHeader.tsx
  frontend/src/components/WriterDocument.tsx
  frontend/src/components/feedbacks/FeedbackFormat.tsx
  frontend/src/components/interviewQuestion/InterviewQuestion.tsx
  frontend/src/components/levellogs/LevellogReport.tsx
  frontend/src/pages/feedback/FeedbackAdd.tsx
  frontend/src/pages/feedback/FeedbackEdit.tsx
  frontend/src/pages/levellogs/LevellogAdd.tsx
  frontend/src/pages/levellogs/LevellogEdit.tsx
  frontend/src/pages/preQuestion/PreQuestionAdd.tsx
  frontend/src/pages/preQuestion/PreQuestionEdit.tsx
  frontend/src/pages/teams/InterviewTeamAdd.tsx
  frontend/src/pages/teams/InterviewTeams.tsx
Labels: 🧑🏻‍💻 프론트엔드, 🛠 리팩터링, Levellog, Feedback, InterviewQuestion, PreQuestion

#350 feat: 서비스 사용 이미지 수정
  frontend/index.d.ts
  frontend/src/assets/images/add.png
  frontend/src/assets/images/angle-left-free-icon-font.webp
  frontend/src/assets/images/check.png
  frontend/src/assets/images/check.svg
  frontend/src/assets/images/close.svg
  frontend/src/assets/images/close.webp
  frontend/src/assets/images/defaultProfile.png
  frontend/src/assets/images/defaultProfile.webp
  frontend/src/assets/images/delete-button.webp
  frontend/src/assets/images/end.svg
  frontend/src/assets/images/error.png
  frontend/src/assets/images/error.webp
  frontend/src/assets/images/feedback.png
  frontend/src/assets/images/feedback.webp
  frontend/src/assets/images/feedbackIcon.svg
  frontend/src/assets/images/group.png
  frontend/src/assets/images/hamburger.svg
  frontend/src/assets/images/hamburgerMenu.png
  frontend/src/assets/images/hamburgerMenu.webp
  frontend/src/assets/images/handshake.png
  frontend/src/assets/images/interviewQuestion.png
  frontend/src/assets/images/interviewQuestion.webp
  frontend/src/assets/images/interviewQuestionIcon.svg
  frontend/src/assets/images/interviewboth.png
  frontend/src/assets/images/interviewboth.webp
  frontend/src/assets/images/interviewee.png
  frontend/src/assets/images/interviewee.webp
  frontend/src/assets/images/interviewer.png
  frontend/src/assets/images/interviewer.webp
  frontend/src/assets/images/leftarrow.svg
  frontend/src/assets/images/levellogIcon.svg
  frontend/src/assets/images/location.svg
  frontend/src/assets/images/mic.png
  frontend/src/assets/images/placeholder.png
  frontend/src/assets/images/plus.svg
  frontend/src/assets/images/preQuestionIcon.svg
  frontend/src/assets/images/question.webp
  frontend/src/assets/images/rightarrow.svg
  frontend/src/components/@commons/Role.tsx
  frontend/src/components/header/Header.tsx
  frontend/src/components/header/Profile.tsx
  frontend/src/components/levellogs/LevellogViewModal.tsx
  frontend/src/components/preQuestion/PreQuestionViewModal.tsx
  frontend/src/components/teams/InterviewTeam.tsx
  frontend/src/components/teams/Interviewer.tsx
  frontend/src/pages/status/EmptyFeedback.tsx
  frontend/src/pages/status/EmptyInterviewQuestion.tsx
  frontend/src/pages/status/Error.tsx
  frontend/src/pages/status/NotFound.tsx
  frontend/src/pages/teams/InterviewTeams.tsx
Labels: 🧑🏻‍💻 프론트엔드

#338 feat: 팀 조회 기능에 필터링 적용
  backend/src/docs/asciidoc/team.adoc
  backend/src/main/java/com/woowacourse/levellog/team/application/TeamService.java
  backend/src/main/java/com/woowacourse/levellog/team/domain/Team.java
  backend/src/main/java/com/woowacourse/levellog/team/domain/TeamRepository.java
  backend/src/main/java/com/woowacourse/levellog/team/domain/TeamStatus.java
  backend/src/main/java/com/woowacourse/levellog/team/dto/TeamAndRoleDto.java
  backend/src/main/java/com/woowacourse/levellog/team/dto/TeamAndRolesDto.java
  backend/src/main/java/com/woowacourse/levellog/team/dto/TeamDto.java
  backend/src/main/java/com/woowacourse/levellog/team/presentation/TeamController.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/TeamAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/ServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/TeamServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/TeamRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/TeamStatusTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/TeamControllerTest.java
Labels: 🌟 기능, 👩🏻‍💻 백엔드, 🛠 리팩터링, Team, MyInfo

#351 feat: 피드백 수정 기능을 구현한다
  frontend/cypress/e2e/PageRoute.cy.ts
  frontend/src/App.tsx
  frontend/src/apis/feedback.ts
  frontend/src/apis/utils.ts
  frontend/src/components/WriterDocument.tsx
  frontend/src/components/feedbacks/Feedback.tsx
  frontend/src/components/interviewQuestion/InterviewQuestion.tsx
  frontend/src/components/levellogs/LevellogViewModal.tsx
  frontend/src/constants/constants.ts
  frontend/src/hooks/useFeedback.ts
  frontend/src/hooks/useFeedbackAddPage.ts
  frontend/src/hooks/useRole.ts
  frontend/src/hooks/useTeam.ts
  frontend/src/pages/feedback/FeedbackAdd.tsx
  frontend/src/pages/feedback/FeedbackEdit.tsx
  frontend/src/pages/feedback/Feedbacks.tsx
  frontend/src/routes/Routes.tsx
Labels: 🌟 기능, 🧑🏻‍💻 프론트엔드, Feedback

#359 fix: 잘못 리베이스되어 사라진 코드를 복구한다
  frontend/src/components/feedbacks/FeedbackFormat.tsx
  frontend/src/components/teams/TeamForm.tsx
  frontend/src/constants/constants.ts
  frontend/src/hooks/useFeedback.ts
  frontend/src/pages/feedback/FeedbackEdit.tsx
Labels: 🐛 버그, 🧑🏻‍💻 프론트엔드, Feedback, 🚨 빨리!

#378 feat: Author에 관한 인가 구현
  frontend/src/apis/preQuestion.ts
  frontend/src/components/WriterDocument.tsx
  frontend/src/components/feedbacks/Feedback.tsx
  frontend/src/components/levellogs/LevellogViewModal.tsx
  frontend/src/components/preQuestion/PreQuestionViewModal.tsx
  frontend/src/components/teams/InterviewTeam.tsx
  frontend/src/components/teams/Interviewer.tsx
  frontend/src/constants/constants.ts
  frontend/src/hooks/useAuth.ts
  frontend/src/hooks/useFeedback.ts
  frontend/src/hooks/useLevellog.ts
  frontend/src/hooks/usePreQuestion.ts
  frontend/src/hooks/useTeam.ts
  frontend/src/hooks/useTeams.ts
  frontend/src/hooks/useUriBuilder.ts
  frontend/src/hooks/useUtil.ts
  frontend/src/pages/feedback/FeedbackAdd.tsx
  frontend/src/pages/feedback/FeedbackEdit.tsx
  frontend/src/pages/feedback/Feedbacks.tsx
  frontend/src/pages/interviewQuestion/InterviewQuestions.tsx
  frontend/src/pages/preQuestion/PreQuestionAdd.tsx
  frontend/src/pages/teams/InterviewDetail.tsx
  frontend/src/routes/Auth.tsx
  frontend/src/routes/Routes.tsx
  frontend/src/types/preQuestion.ts
  frontend/src/types/uri.ts
Labels: 🌟 기능, 🧑🏻‍💻 프론트엔드, 🛠 리팩터링, PreQuestion, 🥷🏻 전지훈련

#388 fix: HttpMessageNotReadableException 핸들러 구현
  backend/src/main/java/com/woowacourse/levellog/common/presentation/ControllerAdvice.java
Labels: 🐛 버그, 👩🏻‍💻 백엔드, 🥷🏻 전지훈련

#371 feat: 관리자 기능 추가
  backend/build.gradle
  backend/src/main/java/com/woowacourse/levellog/admin/application/AdminService.java
  backend/src/main/java/com/woowacourse/levellog/admin/config/AdminAuthInterceptor.java
  backend/src/main/java/com/woowacourse/levellog/admin/config/AdminAuthenticationConfig.java
  backend/src/main/java/com/woowacourse/levellog/admin/dto/AdminAccessTokenDto.java
  backend/src/main/java/com/woowacourse/levellog/admin/dto/AdminPasswordDto.java
  backend/src/main/java/com/woowacourse/levellog/admin/dto/AdminTeamDto.java
  backend/src/main/java/com/woowacourse/levellog/admin/exception/WrongPasswordException.java
  backend/src/main/java/com/woowacourse/levellog/admin/presentation/AdminController.java
  backend/src/main/java/com/woowacourse/levellog/authentication/support/JwtTokenProvider.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/static/src/admin.js
  backend/src/main/resources/templates/admin-login.hbs
  backend/src/main/resources/templates/admin-teams.hbs
  backend/src/test/java/com/woowacourse/levellog/acceptance/AdminAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/AdminServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/ServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/config/TestConfig.java
  backend/src/test/java/com/woowacourse/levellog/fixture/RestAssuredResponse.java
  backend/src/test/java/com/woowacourse/levellog/fixture/RestAssuredTemplate.java
  backend/src/test/java/com/woowacourse/levellog/presentation/ControllerTest.java
  backend/src/test/resources/application.yml
Labels: 🌟 기능, 👩🏻‍💻 백엔드, 🥷🏻 전지훈련, Admin

#389 chore: cypress CI 제거
  .github/workflows/front-cypress.yml
Labels: 🐛 버그, 🧑🏻‍💻 프론트엔드, 🥷🏻 전지훈련, 🚨 빨리!

#377 feat: 팀 생성, 수정, 조회 시 참관자 모드 구현
  backend/src/docs/asciidoc/team.adoc
  backend/src/main/java/com/woowacourse/levellog/team/application/TeamService.java
  backend/src/main/java/com/woowacourse/levellog/team/domain/Participant.java
  backend/src/main/java/com/woowacourse/levellog/team/domain/Participants.java
  backend/src/main/java/com/woowacourse/levellog/team/dto/ParticipantIdsDto.java
  backend/src/main/java/com/woowacourse/levellog/team/dto/TeamDto.java
  backend/src/main/java/com/woowacourse/levellog/team/dto/TeamWriteDto.java
  backend/src/main/java/com/woowacourse/levellog/team/dto/WatcherDto.java
  backend/src/main/java/com/woowacourse/levellog/team/exception/DuplicateParticipantsException.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/AcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/AdminAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/FeedbackAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/InterviewQuestionAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/LevellogAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/MyInfoAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/PreQuestionAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/TeamAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/PreQuestionServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/ServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/TeamServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/ParticipantsTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/RepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/fixture/MemberFixture.java
  backend/src/test/java/com/woowacourse/levellog/presentation/TeamControllerTest.java
Labels: 🌟 기능, 👩🏻‍💻 백엔드, Team, 🥷🏻 전지훈련

#397 fix: 스프린트4에서 찾은 버그들 수정
  frontend/src/App.tsx
  frontend/src/apis/feedback.ts
  frontend/src/apis/interviewQuestion.ts
  frontend/src/components/@commons/BottomBar.tsx
  frontend/src/components/@commons/Button.tsx
  frontend/src/components/@commons/ContentHeader.tsx
  frontend/src/components/@commons/UiEditor.tsx
  frontend/src/components/Footer.tsx
  frontend/src/components/WriterDocument.tsx
  frontend/src/components/header/Header.tsx
  frontend/src/components/header/ProfileDropdown.tsx
  frontend/src/components/interviewQuestion/InterviewQuestion.tsx
  frontend/src/components/levellogs/LevellogReport.tsx
  frontend/src/components/teams/InterviewTeam.tsx
  frontend/src/components/teams/Interviewer.tsx
  frontend/src/constants/constants.ts
  frontend/src/hooks/useLevellog.ts
  frontend/src/hooks/usePreQuestion.ts
  frontend/src/hooks/useTeam.ts
  frontend/src/hooks/useTeams.ts
  frontend/src/hooks/useUriBuilder.ts
  frontend/src/hooks/useUtil.ts
  frontend/src/pages/Home.tsx
  frontend/src/pages/feedback/FeedbackAdd.tsx
  frontend/src/pages/feedback/FeedbackEdit.tsx
  frontend/src/pages/feedback/Feedbacks.tsx
  frontend/src/pages/interviewQuestion/InterviewQuestions.tsx
  frontend/src/pages/levellogs/LevellogAdd.tsx
  frontend/src/pages/levellogs/LevellogEdit.tsx
  frontend/src/pages/preQuestion/PreQuestionAdd.tsx
  frontend/src/pages/preQuestion/PreQuestionEdit.tsx
  frontend/src/pages/status/ErrorToHome.tsx
  frontend/src/pages/status/index.tsx
  frontend/src/pages/teams/InterviewDetail.tsx
  frontend/src/pages/teams/InterviewTeams.tsx
  frontend/src/routes/Auth.tsx
  frontend/src/routes/Routes.tsx
  frontend/src/styles/GlobalStyle.ts
  frontend/yarn.lock
Labels: 🐛 버그, 🧑🏻‍💻 프론트엔드, Levellog, InterviewQuestion, PreQuestion

#399 feat: snackbar 구현
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/apis/utils.ts
  frontend/src/components/@commons/UiEditor.tsx
  frontend/src/components/@commons/snackbar/Snackbar.stories.tsx
  frontend/src/components/@commons/snackbar/Snackbar.tsx
  frontend/src/components/@commons/snackbar/SnackbarContainer.tsx
  frontend/src/components/levellogs/LevellogViewModal.tsx
  frontend/src/components/preQuestion/PreQuestionViewModal.tsx
  frontend/src/constants/constants.ts
  frontend/src/contexts/snackbarContext.tsx
  frontend/src/hooks/useAuth.ts
  frontend/src/hooks/useFeedback.ts
  frontend/src/hooks/useFeedbackAddPage.ts
  frontend/src/hooks/useInterviewQuestion.ts
  frontend/src/hooks/useLevellog.ts
  frontend/src/hooks/usePreQuestion.ts
  frontend/src/hooks/usePreQuestionModal.ts
  frontend/src/hooks/useRole.ts
  frontend/src/hooks/useSnackbar.ts
  frontend/src/hooks/useTeam.ts
  frontend/src/hooks/useTeams.ts
  frontend/src/index.tsx
  frontend/src/pages/Login.tsx
  frontend/src/pages/feedback/FeedbackEdit.tsx
  frontend/src/pages/feedback/Feedbacks.tsx
  frontend/src/pages/levellogs/LevellogAdd.tsx
  frontend/src/pages/levellogs/LevellogEdit.tsx
  frontend/src/pages/preQuestion/PreQuestionAdd.tsx
  frontend/src/pages/preQuestion/PreQuestionEdit.tsx
  frontend/src/portal/ModalPortal.tsx
  frontend/src/portal/SnackbarPortal.tsx
  frontend/src/routes/TeamStatus.tsx
Labels: 🌟 기능, 🧑🏻‍💻 프론트엔드

#400 feat: 팀 참관자 추가
  frontend/src/apis/teams.ts
  frontend/src/components/@commons/Button.tsx
  frontend/src/components/teams/Participants.tsx
  frontend/src/components/teams/TeamForm.tsx
  frontend/src/components/teams/TeamFormInput.tsx
  frontend/src/components/teams/Watcher.tsx
  frontend/src/constants/constants.ts
  frontend/src/constants/validate.ts
  frontend/src/contexts/teamContext.tsx
  frontend/src/hooks/useTeam.ts
  frontend/src/hooks/useTeamPage.ts
  frontend/src/pages/teams/InterviewDetail.tsx
  frontend/src/pages/teams/InterviewTeamAdd.tsx
  frontend/src/pages/teams/InterviewTeamEdit.tsx
  frontend/src/types/team.ts
  frontend/yarn.lock
Labels: 🌟 기능, 🧑🏻‍💻 프론트엔드, Team

#401 hotfix: 팀 생성 날짜 수정
  frontend/src/components/@commons/snackbar/Snackbar.tsx
  frontend/src/constants/validate.ts
Labels: 🧑🏻‍💻 프론트엔드, 🚨 빨리!

#402 hotfix: 참관자의 인가 추가
  frontend/src/hooks/useAuth.ts
Labels: 🐛 버그, 🧑🏻‍💻 프론트엔드, 🚨 빨리!

#403 fix: 사전질문 수정 버튼 문제 수정
  frontend/src/components/levellogs/LevellogViewModal.tsx
Labels: 🐛 버그, 🧑🏻‍💻 프론트엔드, 🚨 빨리!

#406 hotfix: 서비스 QA 반영
  frontend/.webpack/webpack.common.js
  frontend/src/components/@commons/UiEditor.tsx
Labels: 🐛 버그, 🧑🏻‍💻 프론트엔드

#407 release: v1.3.1
  frontend/.webpack/webpack.common.js
  frontend/src/components/@commons/UiEditor.tsx
Labels: 🐛 버그, 🧑🏻‍💻 프론트엔드

#374 feature: 팀 목록 조회 기능에 페이징 적용
  backend/src/docs/asciidoc/team.adoc
  backend/src/main/java/com/woowacourse/levellog/team/application/TeamService.java
  backend/src/main/java/com/woowacourse/levellog/team/domain/TeamRepository.java
  backend/src/main/java/com/woowacourse/levellog/team/presentation/TeamController.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/TeamAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/TeamServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/TeamRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/TeamControllerTest.java
Labels: 🌟 기능, 👩🏻‍💻 백엔드, Team, 🥷🏻 전지훈련

#392 feat: 관리자가 팀을 종료하는 기능
  backend/src/main/java/com/woowacourse/levellog/admin/application/AdminService.java
  backend/src/main/java/com/woowacourse/levellog/admin/presentation/AdminController.java
  backend/src/main/resources/static/css/login.css
  backend/src/main/resources/static/css/team.css
  backend/src/main/resources/static/js/login.js
  backend/src/main/resources/static/js/team.js
  backend/src/main/resources/static/src/admin.js
  backend/src/main/resources/templates/admin-login.hbs
  backend/src/main/resources/templates/admin-teams.hbs
  backend/src/test/java/com/woowacourse/levellog/acceptance/AdminAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/AdminServiceTest.java
Labels: 🌟 기능, 👩🏻‍💻 백엔드, 🥷🏻 전지훈련, Admin

#410 hotfix: 잠실캠 QA 반영
  frontend/.webpack/webpack.dev.js
  frontend/.webpack/webpack.js
  frontend/src/components/@commons/BottomBar.tsx
  frontend/src/components/@commons/ToolTip.tsx
  frontend/src/components/WriterDocument.tsx
  frontend/src/components/interviewQuestion/InterviewQuestion.tsx
  frontend/src/components/teams/Interviewer.tsx
  frontend/src/constants/constants.ts
  frontend/src/contexts/snackbarContext.tsx
  frontend/src/hooks/useFeedback.ts
  frontend/src/pages/feedback/FeedbackAdd.tsx
  frontend/src/pages/feedback/FeedbackEdit.tsx
  frontend/src/pages/feedback/Feedbacks.tsx
  frontend/src/pages/teams/InterviewTeams.tsx
Labels: 🐛 버그, 🧑🏻‍💻 프론트엔드, 🚨 빨리!

#411 hotfix: 피드백 저장 버튼 삭제
  frontend/src/components/@commons/BottomBar.tsx
  frontend/src/hooks/useFeedback.ts
  frontend/src/pages/feedback/FeedbackAdd.tsx
  frontend/src/pages/feedback/FeedbackEdit.tsx
Labels: 🧑🏻‍💻 프론트엔드, 🚨 빨리!

#412 release: v1.3.2
  backend/src/docs/asciidoc/team.adoc
  backend/src/main/java/com/woowacourse/levellog/admin/application/AdminService.java
  backend/src/main/java/com/woowacourse/levellog/admin/presentation/AdminController.java
  backend/src/main/java/com/woowacourse/levellog/team/application/TeamService.java
  backend/src/main/java/com/woowacourse/levellog/team/domain/TeamRepository.java
  backend/src/main/java/com/woowacourse/levellog/team/presentation/TeamController.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/static/css/login.css
  backend/src/main/resources/static/css/team.css
  backend/src/main/resources/static/js/login.js
  backend/src/main/resources/static/js/team.js
  backend/src/main/resources/static/src/admin.js
  backend/src/main/resources/templates/admin-login.hbs
  backend/src/main/resources/templates/admin-teams.hbs
  backend/src/test/java/com/woowacourse/levellog/acceptance/AdminAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/TeamAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/AdminServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/TeamServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/TeamRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/TeamControllerTest.java
  frontend/.webpack/webpack.dev.js
  frontend/.webpack/webpack.js
  frontend/src/components/@commons/BottomBar.tsx
  frontend/src/components/@commons/ToolTip.tsx
  frontend/src/components/WriterDocument.tsx
  frontend/src/components/interviewQuestion/InterviewQuestion.tsx
  frontend/src/components/teams/Interviewer.tsx
  frontend/src/constants/constants.ts
  frontend/src/contexts/snackbarContext.tsx
  frontend/src/hooks/useFeedback.ts
  frontend/src/pages/feedback/FeedbackAdd.tsx
  frontend/src/pages/feedback/FeedbackEdit.tsx
  frontend/src/pages/feedback/Feedbacks.tsx
  frontend/src/pages/teams/InterviewTeams.tsx
Labels: 🐛 버그, 👩🏻‍💻 백엔드, 🧑🏻‍💻 프론트엔드
