Repository woowacourse-teams/2022-levellog, pull requests merged in 2022-09, with the labels that each got.

#413 docs: README 팀 문화 업데이트
  README.md
Labels: 📝 문서

#415 [FE] 로딩 성능개선
  frontend/.webpack/webpack.common.js
  frontend/.webpack/webpack.prod.js
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/assets/images/levellogLogo.png
  frontend/src/assets/images/levellogLogo.webp
  frontend/src/assets/images/levellogLogoLeft.webp
  frontend/src/assets/images/levellogNewLogo.png
  frontend/src/components/@commons/ContentHeader.tsx
  frontend/src/components/@commons/Image.tsx
  frontend/src/components/feedbacks/Feedback.tsx
  frontend/src/components/header/Header.tsx
  frontend/src/components/header/Profile.tsx
  frontend/src/components/levellogs/LevellogViewModal.tsx
  frontend/src/components/teams/InterviewTeam.tsx
  frontend/src/components/teams/Interviewer.tsx
  frontend/src/components/teams/Member.tsx
  frontend/src/components/teams/Participants.tsx
  frontend/src/components/teams/TeamForm.tsx
  frontend/src/components/teams/Watcher.tsx
  frontend/src/constants/constants.ts
  frontend/src/hooks/useTeam.ts
  frontend/src/hooks/useTeamPage.ts
  frontend/src/pages/interviewQuestion/InterviewQuestions.tsx
  frontend/src/pages/status/NotFound.tsx
  frontend/src/routes/Routes.tsx
  frontend/src/utils/util.ts
  frontend/src/utils/validate.ts
  frontend/yarn.lock
Labels: ⚙️ 설정, 🧑🏻‍💻 프론트엔드, 🛠 리팩터링

#416 chore: gzip 압축을 nginx에서 하도록 변경
  frontend/.webpack/webpack.common.js
  frontend/package.json
  frontend/yarn.lock
Labels: ⚙️ 설정, 🧑🏻‍💻 프론트엔드, 🛠 리팩터링

#417 refactor: interviewDetail 페이지를 리펙터링
  frontend/src/components/@commons/CustomLink.tsx
  frontend/src/components/VisibleButtonList.tsx
  frontend/src/components/feedbacks/Feedback.tsx
  frontend/src/components/levellogs/LevellogViewModal.tsx
  frontend/src/components/preQuestion/PreQuestionViewModal.tsx
  frontend/src/components/teams/InterviewTeam.tsx
  frontend/src/components/teams/Interviewer.tsx
  frontend/src/constants/constants.ts
  frontend/src/hooks/useFeedback.ts
  frontend/src/hooks/useLevellog.ts
  frontend/src/hooks/useLevellogModal.ts
  frontend/src/hooks/useModal.ts
  frontend/src/hooks/usePreQuestion.ts
  frontend/src/hooks/usePreQuestionModal.ts
  frontend/src/hooks/useTeam.ts
  frontend/src/hooks/useTeams.ts
  frontend/src/hooks/useUriBuilder.ts
  frontend/src/hooks/useUtil.ts
  frontend/src/pages/feedback/Feedbacks.tsx
  frontend/src/pages/interviewQuestion/InterviewQuestions.tsx
  frontend/src/pages/teams/InterviewDetail.tsx
  frontend/src/pages/teams/InterviewTeams.tsx
  frontend/src/routes/TeamStatus.tsx
  frontend/src/types/team.ts
  frontend/src/utils/util.ts
  frontend/yarn.lock
Labels: 🧑🏻‍💻 프론트엔드, 🛠 리팩터링, Team

#419 fix: 새로고침 시, 브라우저 히스토리가 날아가는 버그 해결
  cypress.config.js
  frontend/src/apis/utils.ts
  frontend/src/pages/Login.tsx
  frontend/src/pages/teams/InterviewTeams.tsx
  frontend/src/routes/Auth.tsx
  frontend/src/routes/AuthLogin.tsx
Labels: 🐛 버그, 🧑🏻‍💻 프론트엔드

#427 feat: 요청에서 에러가 발생해도 정상동작처럼 navigate되는 버그를 수정
  frontend/src/components/teams/TeamForm.tsx
  frontend/src/constants/constants.ts
  frontend/src/hooks/useFeedback.ts
  frontend/src/hooks/useFeedbackAddPage.ts
  frontend/src/hooks/useLevellog.ts
  frontend/src/hooks/usePreQuestion.ts
  frontend/src/hooks/usePreQuestionModal.ts
  frontend/src/hooks/useTeam.ts
  frontend/src/hooks/useUser.ts
Labels: 🐛 버그, 🧑🏻‍💻 프론트엔드

#425 fix: toast ui editor에서 개행이 증식되는 버그 수정
  frontend/.babelrc
  frontend/.webpack/webpack.common.js
  frontend/.webpack/webpack.dev.js
  frontend/.webpack/webpack.js
  frontend/.webpack/webpack.prod.js
  frontend/babel.config.js
  frontend/package.json
  frontend/src/components/@commons/markdownEditor/UiEditor.stories.tsx
  frontend/src/components/@commons/markdownEditor/UiEditor.tsx
  frontend/src/components/@commons/markdownEditor/UiViewer.stories.tsx
  frontend/src/components/@commons/markdownEditor/UiViewer.tsx
  frontend/src/components/WriterDocument.tsx
  frontend/src/components/feedbacks/Feedback.tsx
  frontend/src/components/feedbacks/FeedbackFormat.tsx
  frontend/src/components/levellogs/LevellogReport.tsx
  frontend/src/components/levellogs/LevellogViewModal.tsx
  frontend/src/components/preQuestion/PreQuestionViewModal.tsx
  frontend/src/hooks/useFeedback.ts
  frontend/src/hooks/useLevellog.ts
  frontend/src/hooks/usePreQuestion.ts
  frontend/src/pages/levellogs/LevellogAdd.tsx
  frontend/src/pages/levellogs/LevellogEdit.tsx
  frontend/src/pages/preQuestion/PreQuestionAdd.tsx
  frontend/src/pages/preQuestion/PreQuestionEdit.tsx
  frontend/yarn.lock
Labels: 🐛 버그, 🧑🏻‍💻 프론트엔드

#432 refactor: 쿼리 개선 및 조회 서비스 분리
  backend/src/main/java/com/woowacourse/levellog/common/domain/BaseEntity.java
  backend/src/main/java/com/woowacourse/levellog/feedback/application/FeedbackService.java
  backend/src/main/java/com/woowacourse/levellog/feedback/domain/Feedback.java
  backend/src/main/java/com/woowacourse/levellog/feedback/domain/FeedbackRepository.java
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/domain/InterviewQuestion.java
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/domain/InterviewQuestionRepository.java
  backend/src/main/java/com/woowacourse/levellog/levellog/domain/Levellog.java
  backend/src/main/java/com/woowacourse/levellog/levellog/domain/LevellogRepository.java
  backend/src/main/java/com/woowacourse/levellog/member/presentation/MyInfoController.java
  backend/src/main/java/com/woowacourse/levellog/prequestion/domain/PreQuestion.java
  backend/src/main/java/com/woowacourse/levellog/prequestion/domain/PreQuestionRepository.java
  backend/src/main/java/com/woowacourse/levellog/team/application/TeamQueryService.java
  backend/src/main/java/com/woowacourse/levellog/team/application/TeamService.java
  backend/src/main/java/com/woowacourse/levellog/team/domain/Participant.java
  backend/src/main/java/com/woowacourse/levellog/team/domain/ParticipantRepository.java
  backend/src/main/java/com/woowacourse/levellog/team/domain/SimpleParticipant.java
  backend/src/main/java/com/woowacourse/levellog/team/domain/SimpleParticipants.java
  backend/src/main/java/com/woowacourse/levellog/team/domain/Team.java
  backend/src/main/java/com/woowacourse/levellog/team/domain/TeamQueryRepository.java
  backend/src/main/java/com/woowacourse/levellog/team/domain/TeamRepository.java
  backend/src/main/java/com/woowacourse/levellog/team/domain/TeamStatus.java
  backend/src/main/java/com/woowacourse/levellog/team/dto/AllParticipantDto.java
  backend/src/main/java/com/woowacourse/levellog/team/dto/AllSimpleParticipantDto.java
  backend/src/main/java/com/woowacourse/levellog/team/dto/ParticipantDto.java
  backend/src/main/java/com/woowacourse/levellog/team/dto/ParticipantSimpleDto.java
  backend/src/main/java/com/woowacourse/levellog/team/dto/TeamListDto.java
  backend/src/main/java/com/woowacourse/levellog/team/dto/TeamSimpleDto.java
  backend/src/main/java/com/woowacourse/levellog/team/dto/TeamsDto.java
  backend/src/main/java/com/woowacourse/levellog/team/dto/WatcherDto.java
  backend/src/main/java/com/woowacourse/levellog/team/presentation/TeamController.java
  backend/src/main/resources/logback-spring.xml
  backend/src/test/java/com/woowacourse/levellog/acceptance/MyInfoAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/TeamAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/ServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/TeamQueryServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/TeamServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/InterviewQuestionTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/LevellogTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/PreQuestionRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/PreQuestionTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/RepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/SimpleParticipantTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/TeamQueryRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/TeamRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/ControllerTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/TeamControllerTest.java
Labels: 👩🏻‍💻 백엔드, 🛠 리팩터링

#435 feat: 팀 목록 조회 필터링
  backend/src/docs/asciidoc/team.adoc
  backend/src/main/java/com/woowacourse/levellog/team/application/TeamQueryService.java
  backend/src/main/java/com/woowacourse/levellog/team/domain/TeamFilterCondition.java
  backend/src/main/java/com/woowacourse/levellog/team/domain/TeamQueryRepository.java
  backend/src/main/java/com/woowacourse/levellog/team/domain/TeamStatus.java
  backend/src/main/java/com/woowacourse/levellog/team/presentation/TeamController.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/AcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/AdminAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/MyInfoAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/TeamAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/TeamQueryServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/TeamServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/TeamFilterConditionTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/TeamQueryRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/TeamStatusTest.java
  backend/src/test/java/com/woowacourse/levellog/fixture/TimeFixture.java
  backend/src/test/java/com/woowacourse/levellog/presentation/TeamControllerTest.java
Labels: 🌟 기능, 👩🏻‍💻 백엔드, Team, MyInfo

#436 feat: 인터뷰 질문을 검색하고 좋아요 기능을 추가
  backend/build.gradle
  backend/src/docs/asciidoc/index.adoc
  backend/src/docs/asciidoc/interviewquestionsearch.adoc
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/application/InterviewQuestionService.java
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/domain/InterviewQuestion.java
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/domain/InterviewQuestionLikes.java
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/domain/InterviewQuestionLikesRepository.java
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/domain/InterviewQuestionQueryRepository.java
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/domain/InterviewQuestionRepository.java
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/domain/InterviewQuestionSort.java
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/dto/InterviewQuestionSearchResultDto.java
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/dto/InterviewQuestionSearchResultsDto.java
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/exception/InterviewQuestionLikeNotFoundException.java
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/exception/InterviewQuestionLikesAlreadyExistException.java
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/presentation/InterviewQuestionSearchController.java
  backend/src/main/resources/logback-spring.xml
  backend/src/test/java/com/woowacourse/levellog/acceptance/InterviewQuestionSearchAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/InterviewQuestionServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/ServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/InterviewQuestionLikesRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/InterviewQuestionLikesTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/RepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/fixture/RestAssuredTemplate.java
  backend/src/test/java/com/woowacourse/levellog/presentation/ControllerTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/InterviewQuestionSearchControllerTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/PreQuestionControllerTest.java
Labels: 🌟 기능, 👩🏻‍💻 백엔드, InterviewQuestion, 🚨 빨리!

#440 fix: 인터뷰 질문 전체 조회 버그 수정
  backend/src/docs/asciidoc/interviewquestionsearch.adoc
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/application/InterviewQuestionService.java
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/presentation/InterviewQuestionSearchController.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/InterviewQuestionSearchAcceptanceTest.java
Labels: 🐛 버그, InterviewQuestion

#443 fix: 팀 목록 조회 버그 수정
  backend/src/docs/asciidoc/team.adoc
  backend/src/main/java/com/woowacourse/levellog/team/domain/TeamQueryRepository.java
  backend/src/main/java/com/woowacourse/levellog/team/presentation/TeamController.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/TeamAcceptanceTest.java
Labels: 🐛 버그, 👩🏻‍💻 백엔드, Team

#445 feat: 전체 팀 조회 API 변경 대응 및 전체 팀 필터링 구현
  frontend/docs/README.md
  frontend/src/apis/myInfo.ts
  frontend/src/apis/teams.ts
  frontend/src/components/@commons/ContentHeader.tsx
  frontend/src/components/teams/InterviewTeam.tsx
  frontend/src/constants/constants.ts
  frontend/src/contexts/teamContext.tsx
  frontend/src/hooks/useTeam.ts
  frontend/src/hooks/useTeamPage.ts
  frontend/src/hooks/useTeams.ts
  frontend/src/hooks/useUser.ts
  frontend/src/pages/teams/InterviewDetail.tsx
  frontend/src/pages/teams/InterviewTeams.tsx
  frontend/src/types/team.ts
Labels: 🌟 기능, 🧑🏻‍💻 프론트엔드, Team, MyInfo

#448 feat: 저작권 페이지, 파비콘 추가
  frontend/public/favicon-32x32.png
  frontend/public/index.html
  frontend/src/assets/images/defaultProfile.png
  frontend/src/assets/images/defaultProfile.webp
  frontend/src/assets/images/interviewboth.png
  frontend/src/assets/images/interviewboth.webp
  frontend/src/assets/images/interviewee.png
  frontend/src/assets/images/interviewee.webp
  frontend/src/assets/images/interviewer.png
  frontend/src/assets/images/interviewer.webp
  frontend/src/components/Footer.tsx
  frontend/src/constants/constants.ts
  frontend/src/pages/Copyright.tsx
  frontend/src/routes/Routes.tsx
Labels: 🌟 기능, ⚙️ 설정, 🧑🏻‍💻 프론트엔드

#449 hotfix: 파비콘 누락 버그 수정
  frontend/public/index.html
  frontend/src/assets/images/favicon-32x32.png
  frontend/src/pages/Copyright.tsx
Labels: 🐛 버그, 🧑🏻‍💻 프론트엔드, 🚨 빨리!

#450 fix: LIKE 키워드 사용 시 SQL Injection 방지
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/domain/InterviewQuestionQueryRepository.java
  backend/src/test/java/com/woowacourse/levellog/domain/InterviewQuestionLikesRepositoryTest.java
Labels: 🐛 버그, 👩🏻‍💻 백엔드, InterviewQuestion, 🚨 빨리!

#452 fix: 팀 목록 조회 쿼리가 JOIN 후 정렬을 보장하지 않는 문제 해결
  backend/src/main/java/com/woowacourse/levellog/team/application/TeamQueryService.java
  backend/src/main/java/com/woowacourse/levellog/team/domain/TeamQueryRepository.java
Labels: 🐛 버그, 👩🏻‍💻 백엔드, Team

#453 hotfix: teams 요청 size param 수정
  frontend/public/index.html
  frontend/src/apis/teams.ts
Labels: 🧑🏻‍💻 프론트엔드, 🚨 빨리!

#456 fix: 인터뷰 질문 기능 수정
  frontend/src/apis/interviewQuestionSearch.ts
  frontend/src/components/interviewQuestion/InterviewQuestionSearchForm.tsx
  frontend/src/components/interviewQuestion/InterviewQuestionSearchResult.tsx
  frontend/src/components/interviewQuestion/InterviewQuestionSearchResults.tsx
  frontend/src/hooks/useInterviewQuestionSearch.ts
  frontend/src/hooks/useInterviewQuestionSearchResult.ts
  frontend/src/pages/Home.tsx
  frontend/src/pages/interviewQuestion/InterviewQuestionSearch.tsx
  frontend/src/routes/Routes.tsx
  frontend/src/utils/util.ts
Labels: 🌟 기능, 🧑🏻‍💻 프론트엔드, InterviewQuestion

#451 fix: LIKE 키워드 사용 시 SQL Injection 방지 버그 수정
  backend/src/docs/asciidoc/interviewquestionsearch.adoc
  backend/src/main/java/com/woowacourse/levellog/common/support/StringConverter.java
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/domain/InterviewQuestionQueryRepository.java
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/presentation/InterviewQuestionSearchController.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/InterviewQuestionSearchAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/InterviewQuestionLikesRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/InterviewQuestionSearchControllerTest.java
Labels: 🐛 버그, 👩🏻‍💻 백엔드

#457 fix: 인터뷰 질문 검색 시 정렬 인자 수정
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/domain/InterviewQuestionSort.java
  backend/src/test/java/com/woowacourse/levellog/application/InterviewQuestionServiceTest.java
Labels: 🐛 버그, 👩🏻‍💻 백엔드, InterviewQuestion, 🚨 빨리!

#458 refactor: LIKE -> FULL TEXT 인덱스를 활용하는 쿼리로 변경
  backend/build.gradle
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/domain/InterviewQuestionQueryRepository.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/InterviewQuestionSearchAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/InterviewQuestionServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/InterviewQuestionLikesRepositoryTest.java
Labels: 🌟 기능, 👩🏻‍💻 백엔드, 🛠 리팩터링, InterviewQuestion

#459 chore: 시인성이 좋지 못한 "역할 이미지" 변경
  frontend/src/assets/images/interviewboth.png
  frontend/src/assets/images/interviewboth.webp
  frontend/src/assets/images/interviewer.png
  frontend/src/assets/images/interviewer.webp
  frontend/src/pages/Copyright.tsx
Labels: 🧑🏻‍💻 프론트엔드, 💡제안

#460 fix: 인터뷰 질문 검색 쿼리를 기존 LIKE 문법으로 변경
  backend/build.gradle
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/domain/InterviewQuestionQueryRepository.java
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/presentation/InterviewQuestionSearchController.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/InterviewQuestionSearchAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/InterviewQuestionServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/InterviewQuestionLikesRepositoryTest.java
Labels: 🐛 버그, 🛠 리팩터링, InterviewQuestion, 🚨 빨리!

#464 release: v1.4.1
  frontend/src/apis/interviewQuestionSearch.ts
Labels: 🐛 버그

#466 release: v1.4.2
  frontend/src/apis/interviewQuestionSearch.ts
Labels: 🐛 버그, 🧑🏻‍💻 프론트엔드

#468 refactor: 레벨로그 상세조회 1 + 1 쿼리 개선
  backend/src/main/java/com/woowacourse/levellog/levellog/application/LevellogService.java
  backend/src/main/java/com/woowacourse/levellog/levellog/domain/LevellogRepository.java
Labels: 👩🏻‍💻 백엔드, 🛠 리팩터링, Levellog

#469 chore: 톰캣 설정값 변경
  backend/src/main/resources/application.yml
Labels: 👩🏻‍💻 백엔드, ⚙️ 설정, 🏭 인프라

#470 release: v1.4.3
  backend/src/main/java/com/woowacourse/levellog/levellog/application/LevellogService.java
  backend/src/main/java/com/woowacourse/levellog/levellog/domain/LevellogRepository.java
  backend/src/main/resources/application.yml
Labels: 👩🏻‍💻 백엔드, ⚙️ 설정, 🛠 리팩터링

#472 refactor: getXXX 메서드를 XXXRepository에 default 메서드로 구현
  backend/src/main/java/com/woowacourse/levellog/admin/application/AdminService.java
  backend/src/main/java/com/woowacourse/levellog/feedback/application/FeedbackService.java
  backend/src/main/java/com/woowacourse/levellog/feedback/domain/FeedbackRepository.java
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/application/InterviewQuestionService.java
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/domain/InterviewQuestionRepository.java
  backend/src/main/java/com/woowacourse/levellog/levellog/application/LevellogService.java
  backend/src/main/java/com/woowacourse/levellog/levellog/domain/LevellogRepository.java
  backend/src/main/java/com/woowacourse/levellog/member/domain/MemberRepository.java
  backend/src/main/java/com/woowacourse/levellog/prequestion/application/PreQuestionService.java
  backend/src/main/java/com/woowacourse/levellog/prequestion/domain/PreQuestionRepository.java
  backend/src/main/java/com/woowacourse/levellog/team/application/TeamQueryService.java
  backend/src/main/java/com/woowacourse/levellog/team/application/TeamService.java
  backend/src/main/java/com/woowacourse/levellog/team/domain/TeamRepository.java
  backend/src/test/java/com/woowacourse/levellog/domain/FeedbackRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/InterviewQuestionRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/LevellogRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/MemberRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/PreQuestionRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/TeamRepositoryTest.java
Labels: 👩🏻‍💻 백엔드, 🛠 리팩터링

#439 chore: dev profile의 ddl-auto 옵션을 validate로 변경
  backend/src/main/resources/application-dev.yml
Labels: 👩🏻‍💻 백엔드, ⚙️ 설정
