Repository woowacourse-teams/2022-levellog, pull requests merged in 2022-10, with the labels that each got.

#478 refactor: AllParticipantDto 리팩터링
  backend/src/main/java/com/woowacourse/levellog/team/application/TeamQueryService.java
  backend/src/main/java/com/woowacourse/levellog/team/domain/Team.java
  backend/src/main/java/com/woowacourse/levellog/team/domain/TeamQueryRepository.java
  backend/src/main/java/com/woowacourse/levellog/team/domain/TeamStatus.java
  backend/src/main/java/com/woowacourse/levellog/team/dto/AllParticipantDto.java
  backend/src/main/java/com/woowacourse/levellog/team/dto/TeamDetailResponse.java
  backend/src/main/java/com/woowacourse/levellog/team/dto/TeamDto.java
  backend/src/main/java/com/woowacourse/levellog/team/presentation/TeamController.java
  backend/src/test/java/com/woowacourse/levellog/application/TeamQueryServiceTest.java
Labels: 👩🏻‍💻 백엔드, 🛠 리팩터링, Team

#483 [FE] InterviewTeams 페이지에 리액트 쿼리 적용
  frontend/package-lock.json
  frontend/package.json
  frontend/src/apis/utils.ts
  frontend/src/components/teams/InterviewTeam.tsx
  frontend/src/components/teams/Teams.tsx
  frontend/src/constants/constants.ts
  frontend/src/hooks/useFeedback.ts
  frontend/src/hooks/useInterviewQuestion.ts
  frontend/src/hooks/useLevellog.ts
  frontend/src/hooks/usePreQuestion.ts
  frontend/src/hooks/useRole.ts
  frontend/src/hooks/useTeam.ts
  frontend/src/hooks/useTeams.ts
  frontend/src/index.tsx
  frontend/src/pages/Login.tsx
  frontend/src/pages/status/EmptyTeams.tsx
  frontend/src/pages/teams/InterviewTeams.tsx
  frontend/src/routes/AuthLogin.tsx
  frontend/src/types/team.ts
  frontend/yarn.lock
Labels: 🌟 기능, 🧑🏻‍💻 프론트엔드, 🛠 리팩터링

#484 feat: 깃허브 로그인 시 닉네임을 추가로 보내도록 수정
  backend/src/main/java/com/woowacourse/levellog/authentication/application/OAuthService.java
  backend/src/main/java/com/woowacourse/levellog/authentication/dto/LoginDto.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/OAuthAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/OAuthServiceTest.java
Labels: 👩🏻‍💻 백엔드, 🛠 리팩터링, Auth, 🚨 빨리!

#481 fix: API 에 맞도록 팀 상세 조회 시 멤버 프로필 url 추가
  backend/src/main/java/com/woowacourse/levellog/team/domain/TeamQueryRepository.java
  backend/src/main/java/com/woowacourse/levellog/team/dto/AllParticipantDto.java
Labels: 🐛 버그, 👩🏻‍💻 백엔드, Team, 🚨 빨리!

#495 refactor: 팀 생성의 데이터 패칭 부분 리펙터링
  frontend/src/apis/feedback.ts
  frontend/src/apis/member.ts
  frontend/src/apis/teams.ts
  frontend/src/components/@commons/ContentHeader.tsx
  frontend/src/components/WriterDocument.tsx
  frontend/src/components/teams/AddMember.tsx
  frontend/src/components/teams/Member.tsx
  frontend/src/components/teams/SearchMember.tsx
  frontend/src/components/teams/TeamForm.tsx
  frontend/src/components/teams/TeamFormInput.tsx
  frontend/src/contexts/memberContext.tsx
  frontend/src/hooks/auth/useAuth.ts
  frontend/src/hooks/preQuestion/usePreQuestionAdd.ts
  frontend/src/hooks/team/useMember.ts
  frontend/src/hooks/team/useTeam.ts
  frontend/src/hooks/team/useTeamAdd.ts
  frontend/src/hooks/team/useTeamDetail.ts
  frontend/src/hooks/team/useTeamEdit.ts
  frontend/src/hooks/utils/errorHandler.ts
  frontend/src/pages/feedback/FeedbackAdd.tsx
  frontend/src/pages/teams/InterviewDetail.tsx
  frontend/src/pages/teams/InterviewTeamAdd.tsx
  frontend/src/pages/teams/InterviewTeamEdit.tsx
  frontend/src/routes/Routes.tsx
  frontend/src/routes/TeamStatus.tsx
  frontend/src/utils/util.ts
Labels: 🧑🏻‍💻 프론트엔드, 🛠 리팩터링, Team

#494 refactor: InterviewTeams 페이지를 리팩터링한다
  frontend/src/apis/interviewQuestionSearch.ts
  frontend/src/apis/myInfo.ts
  frontend/src/apis/teams.ts
  frontend/src/apis/utils.ts
  frontend/src/components/interviewQuestion/InterviewQuestion.tsx
  frontend/src/components/interviewQuestion/InterviewQuestionContent.tsx
  frontend/src/components/interviewQuestion/InterviewQuestionSearchResults.tsx
  frontend/src/components/teams/Teams.tsx
  frontend/src/hooks/questionSearch/useSearchedInterviewQuestion.ts
  frontend/src/hooks/team/useTeam.ts
  frontend/src/hooks/team/useTeamAdd.ts
  frontend/src/hooks/team/useTeams.ts
  frontend/src/hooks/team/useTeamsCondition.ts
  frontend/src/pages/teams/InterviewTeams.tsx
Labels: 🐛 버그, 🧑🏻‍💻 프론트엔드, 🛠 리팩터링

#485 refactor: mariaDB를 연결했을 때 깨지는 쿼리 및 테스트 수정
  backend/src/main/java/com/woowacourse/levellog/common/domain/BaseEntity.java
  backend/src/main/java/com/woowacourse/levellog/team/domain/TeamQueryRepository.java
  backend/src/test/java/com/woowacourse/levellog/application/PreQuestionServiceTest.java
Labels: 👩🏻‍💻 백엔드, ⚙️ 설정, 📚 테스트

#489 refactor: Team, Participant 간 일대다 양방향 연관관계 추가 및 리팩토링
  backend/src/main/java/com/woowacourse/levellog/admin/application/AdminService.java
  backend/src/main/java/com/woowacourse/levellog/admin/dto/response/AdminTeamResponse.java
  backend/src/main/java/com/woowacourse/levellog/feedback/application/FeedbackService.java
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/application/InterviewQuestionService.java
  backend/src/main/java/com/woowacourse/levellog/levellog/application/LevellogService.java
  backend/src/main/java/com/woowacourse/levellog/levellog/domain/LevellogRepository.java
  backend/src/main/java/com/woowacourse/levellog/prequestion/application/PreQuestionService.java
  backend/src/main/java/com/woowacourse/levellog/team/application/TeamService.java
  backend/src/main/java/com/woowacourse/levellog/team/domain/Participant.java
  backend/src/main/java/com/woowacourse/levellog/team/domain/ParticipantRepository.java
  backend/src/main/java/com/woowacourse/levellog/team/domain/Participants.java
  backend/src/main/java/com/woowacourse/levellog/team/domain/ParticipantsFactory.java
  backend/src/main/java/com/woowacourse/levellog/team/domain/Team.java
  backend/src/main/java/com/woowacourse/levellog/team/domain/TeamDetail.java
  backend/src/main/java/com/woowacourse/levellog/team/domain/TeamStatus.java
  backend/src/main/java/com/woowacourse/levellog/team/dto/request/TeamWriteRequest.java
  backend/src/main/java/com/woowacourse/levellog/team/exception/NotParticipantException.java
  backend/src/main/java/com/woowacourse/levellog/team/presentation/TeamController.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/TeamAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/FeedbackServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/InterviewQuestionServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/LevellogServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/PreQuestionServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/ServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/TeamQueryServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/TeamServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/config/TestConfig.java
  backend/src/test/java/com/woowacourse/levellog/domain/FeedbackTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/InterviewQuestionLikesTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/InterviewQuestionTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/LevellogRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/LevellogTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/ParticipantRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/ParticipantTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/ParticipantsFactoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/ParticipantsTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/PreQuestionTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/RepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/TeamDetailTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/TeamTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/TeamControllerTest.java
Labels: 👩🏻‍💻 백엔드, 🛠 리팩터링, Team, 🥷🏻 전지훈련, 🚨 빨리!

#496 fix: react query로 인한 버그 수정
  frontend/src/apis/teams.ts
  frontend/src/components/@commons/Image.tsx
  frontend/src/components/@commons/markdownEditor/UiViewer.tsx
  frontend/src/components/preQuestion/PreQuestionViewModal.tsx
  frontend/src/pages/teams/InterviewDetail.tsx
  frontend/src/utils/util.ts
Labels: 🐛 버그, 🧑🏻‍💻 프론트엔드

#502 feat: 팀 목록 조회 결과에 nickname 필드 추가
  backend/src/main/java/com/woowacourse/levellog/team/domain/TeamQueryRepository.java
  backend/src/main/java/com/woowacourse/levellog/team/dto/query/TeamListQueryResult.java
  backend/src/main/java/com/woowacourse/levellog/team/dto/response/ParticipantInTeamListResponse.java
  backend/src/main/java/com/woowacourse/levellog/team/dto/response/TeamListResponse.java
  backend/src/test/java/com/woowacourse/levellog/domain/TeamQueryRepositoryTest.java
Labels: 🌟 기능, 👩🏻‍💻 백엔드, Team, 🚨 빨리!

#503 feat: `InterviewTeams` 페이지의 웹 접근성을 개선
  frontend/docs/A11Y.md
  frontend/src/components/@commons/ContentHeader.tsx
  frontend/src/components/@commons/Image.tsx
  frontend/src/components/Footer.tsx
  frontend/src/components/header/Header.tsx
  frontend/src/components/header/Profile.tsx
  frontend/src/components/header/ProfileDropdown.tsx
  frontend/src/components/teams/InterviewTeam.tsx
  frontend/src/components/teams/TeamForm.tsx
  frontend/src/components/teams/Teams.tsx
  frontend/src/pages/teams/InterviewTeamAdd.tsx
  frontend/src/pages/teams/InterviewTeams.tsx
  frontend/src/pages/teams/TeamFilterButtons.tsx
  frontend/src/types/team.ts
Labels: 🌟 기능, 🧑🏻‍💻 프론트엔드, 🛠 리팩터링

#506 feat: 인터뷰 질문 검색 기능에 대한 웹 접근성 추가
  frontend/src/apis/interviewQuestionSearch.ts
  frontend/src/components/@commons/snackbar/Snackbar.tsx
  frontend/src/components/interviewQuestion/InterviewQuestionSearchForm.tsx
  frontend/src/components/interviewQuestion/InterviewQuestionSearchResult.tsx
  frontend/src/components/interviewQuestion/InterviewQuestionSearchResults.tsx
Labels: 🌟 기능, 🧑🏻‍💻 프론트엔드, InterviewQuestion

#507 test: 유틸함수 테스트 코드 작성
  frontend/jest.config.json
  frontend/package.json
  frontend/src/components/feedbacks/Feedback.tsx
  frontend/src/pages/interviewQuestion/InterviewQuestions.tsx
  frontend/src/utils/util.test.ts
  frontend/src/utils/util.ts
  frontend/yarn.lock
Labels: 🧑🏻‍💻 프론트엔드, 📚 테스트

#508 fix: 오타 수정 및 웹 접근성 추가 개선
  frontend/public/index.html
  frontend/src/components/interviewQuestion/InterviewQuestionSearchForm.tsx
  frontend/src/components/teams/InterviewTeam.tsx
Labels: 🧑🏻‍💻 프론트엔드, 🛠 리팩터링

#514 docs: README 갱신
  README.md
Labels: 📝 문서, ⚙️ 설정, 🚨 빨리!

#520 feat: 변경된 로고 이미지 적용
  frontend/public/index.html
  frontend/src/assets/images/empty.webp
  frontend/src/assets/images/favicon-32x32.png
  frontend/src/assets/images/favicon.webp
  frontend/src/assets/images/levellogLogo.png
  frontend/src/assets/images/levellogLogo.webp
  frontend/src/assets/images/levellogLogoCenter.webp
  frontend/src/assets/images/levellogLogoLeft.png
  frontend/src/assets/images/levellogLogoLeft.webp
  frontend/src/assets/images/notFound.webp
  frontend/src/components/@commons/Image.tsx
  frontend/src/components/@commons/Style.tsx
  frontend/src/components/header/Header.tsx
  frontend/src/pages/status/EmptyFeedback.tsx
  frontend/src/pages/status/EmptyInterviewQuestion.tsx
  frontend/src/pages/status/EmptySearchResult.tsx
  frontend/src/pages/status/EmptyTeams.tsx
  frontend/src/pages/status/Error.tsx
  frontend/src/pages/status/ErrorToHome.tsx
  frontend/src/pages/status/NotFound.tsx
  frontend/src/pages/status/index.tsx
  frontend/src/styles/sizeList.ts
  frontend/src/types/index.ts
Labels: 🧑🏻‍💻 프론트엔드

#521 chore: HikariCP 설정
  backend/src/main/resources/application.yml
Labels: 👩🏻‍💻 백엔드, ⚙️ 설정

#523 fix: 팀 상세 조회시 참가자가 정렬되지 않는 문제 수정
  backend/src/main/java/com/woowacourse/levellog/team/domain/TeamQueryRepository.java
Labels: 🐛 버그, 👩🏻‍💻 백엔드, 🚨 빨리!

#525 fix: 나의 팀 리스트 조회 시 참관자 포함되있는 버그를 수정
  backend/src/main/java/com/woowacourse/levellog/team/domain/TeamQueryRepository.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/MyInfoAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/TeamQueryRepositoryTest.java
Labels: 🐛 버그

#518 refactor: 사전질문 기능 수정
  frontend/src/components/interviewQuestion/InterviewQuestionSearchForm.tsx
  frontend/src/components/levellogs/LevellogContent.tsx
  frontend/src/components/preQuestion/PreQuestionViewModal.tsx
  frontend/src/hooks/preQuestion/usePreQuestion.ts
  frontend/src/hooks/preQuestion/usePreQuestionAdd.ts
  frontend/src/hooks/preQuestion/usePreQuestionEdit.ts
  frontend/src/hooks/preQuestion/usePreQuestionModal.ts
  frontend/src/hooks/preQuestion/usePreQuestionQuery.ts
  frontend/src/hooks/questionSearch/useInterviewQuestionSearch.ts
  frontend/src/index.tsx
  frontend/src/pages/preQuestion/PreQuestionAdd.tsx
  frontend/src/pages/preQuestion/PreQuestionEdit.tsx
Labels: 🧑🏻‍💻 프론트엔드, 🛠 리팩터링, PreQuestion

#531 fix: 내가 작성한 피드백 수정을 할 수 없는 버그 수정
  frontend/src/apis/teams.ts
  frontend/src/hooks/team/useMember.ts
  frontend/src/hooks/team/useTeam.ts
  frontend/src/pages/feedback/Feedbacks.tsx
  frontend/src/pages/interviewQuestion/InterviewQuestions.tsx
  frontend/src/utils/util.ts
Labels: 🐛 버그, 🧑🏻‍💻 프론트엔드

#534 fix: 생성 시 호출하는 검증 쿼리에 배타 락 적용
  backend/src/main/java/com/woowacourse/levellog/feedback/domain/FeedbackRepository.java
  backend/src/main/java/com/woowacourse/levellog/levellog/domain/LevellogRepository.java
  backend/src/main/java/com/woowacourse/levellog/member/domain/MemberRepository.java
  backend/src/main/java/com/woowacourse/levellog/prequestion/domain/PreQuestionRepository.java
Labels: 🐛 버그, 👩🏻‍💻 백엔드

#535 fix: 스낵바가 여러개 생기는 버그 수정
  frontend/src/components/WriterDocument.tsx
  frontend/src/hooks/preQuestion/usePreQuestionQuery.ts
  frontend/src/hooks/utils/useSnackbar.ts
Labels: 🐛 버그, 🧑🏻‍💻 프론트엔드

#539 fix: QA 버그 수정
  frontend/src/pages/feedback/FeedbackAdd.tsx
  frontend/src/pages/teams/InterviewTeams.tsx
Labels: 🐛 버그, 🧑🏻‍💻 프론트엔드

#540 fix: confirm이 여러개가 생기는 버그 수정
  frontend/src/hooks/utils/usePreventGoBack.ts
  frontend/src/pages/feedback/FeedbackEdit.tsx
Labels: 🐛 버그, 🧑🏻‍💻 프론트엔드

#542 fix: 피드백 추가 페이지 뒤로가기 막는 기능 수정
  frontend/src/hooks/utils/usePreventGoBack.ts
Labels: 🐛 버그, 🧑🏻‍💻 프론트엔드

#546 fix: 파비콘 파일 위치 수정
  frontend/.webpack/webpack.common.js
  frontend/package.json
  frontend/public/favicon.webp
  frontend/public/index.html
  frontend/src/components/@commons/Style.tsx
  frontend/yarn.lock
Labels: 🐛 버그, 🧑🏻‍💻 프론트엔드

#511 refactor: 트랜잭션 범위에서 외부 리소스 요청 분리
  backend/src/main/java/com/woowacourse/levellog/authentication/application/LoginService.java
  backend/src/main/java/com/woowacourse/levellog/authentication/application/OAuthService.java
  backend/src/main/java/com/woowacourse/levellog/authentication/domain/GithubOAuthClient.java
  backend/src/main/java/com/woowacourse/levellog/authentication/presentation/OAuthController.java
  backend/src/test/java/com/woowacourse/levellog/application/FeedbackServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/LoginServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/ServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/ControllerTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/OAuthControllerTest.java
Labels: 👩🏻‍💻 백엔드, 🛠 리팩터링, Auth

#552 chore: Github Actions CI 환경을 개선한다
  .github/workflows/front-dev.yml
  .github/workflows/front-prod.yml
  .github/workflows/main.yml
  frontend/src/utils/util.test.ts
  frontend/src/utils/util.ts
Labels: ⚙️ 설정, 🧑🏻‍💻 프론트엔드

#558 chore: 피드백 길이 변경
  backend/src/main/java/com/woowacourse/levellog/feedback/domain/Feedback.java
  backend/src/test/java/com/woowacourse/levellog/domain/FeedbackTest.java
Labels: 👩🏻‍💻 백엔드, Feedback

#561 fix: yarn.lock 파일 교체
  frontend/yarn.lock
Labels: ⚙️ 설정, 🧑🏻‍💻 프론트엔드, 🚨 빨리!

#560 refactor: 사용되지 않는 코드 제거
  .github/workflows/front-dev.yml
  .github/workflows/front-prod.yml
  .github/workflows/front-unit-test.yml
  frontend/.webpack/webpack.common.js
  frontend/cypress.config.ts
  frontend/cypress/e2e/PageRoute.cy.ts
  frontend/cypress/support/commands.ts
  frontend/cypress/support/e2e.ts
  frontend/cypress/videos/PageRoute.cy.ts.mp4
  frontend/docs/A11Y.md
  frontend/docs/README.md
  frontend/package.json
  frontend/public/mockServiceWorker.js
  frontend/src/components/@commons/FilterButton.tsx
  frontend/src/components/@commons/button/Button.tsx
  frontend/src/components/@commons/contentHeader/ContentHeader.tsx
  frontend/src/components/@commons/image/Image.tsx
  frontend/src/components/@commons/markdownEditor/UiEditor.tsx
  frontend/src/components/@commons/modal/Modal.tsx
  frontend/src/components/@commons/role/Role.tsx
  frontend/src/components/@commons/snackbar/Snackbar.tsx
  frontend/src/components/@commons/toolTip/ToolTip.tsx
  frontend/src/components/Footer.tsx
  frontend/src/components/WriterDocument.tsx
  frontend/src/components/feedbacks/Feedback.tsx
  frontend/src/components/header/Header.tsx
  frontend/src/components/header/Profile.tsx
  frontend/src/components/header/ProfileDropdown.tsx
  frontend/src/components/interviewQuestion/InterviewQuestion.tsx
  frontend/src/components/interviewQuestion/InterviewQuestionSearchForm.tsx
  frontend/src/components/interviewQuestion/InterviewQuestionSearchResult.tsx
  frontend/src/components/interviewQuestion/InterviewQuestionSearchResults.tsx
  frontend/src/components/levellogs/LevellogContent.tsx
  frontend/src/components/levellogs/LevellogViewModal.tsx
  frontend/src/components/preQuestion/PreQuestionViewModal.tsx
  frontend/src/components/teams/AddMember.tsx
  frontend/src/components/teams/InterviewTeam.tsx
  frontend/src/components/teams/Interviewer.tsx
  frontend/src/components/teams/InterviewerButton.tsx
  frontend/src/components/teams/TeamForm.tsx
  frontend/src/components/teams/TeamFormInput.tsx
  frontend/src/components/teams/Watcher.tsx
  frontend/src/constants/constants.ts
  frontend/src/hooks/team/useTeamsCondition.ts
  frontend/src/mocks/browser.ts
  frontend/src/mocks/handler.ts
  frontend/src/mocks/mockData.ts
  frontend/src/pages/feedback/FeedbackAdd.tsx
  frontend/src/pages/feedback/FeedbackEdit.tsx
  frontend/src/pages/feedback/Feedbacks.tsx
  frontend/src/pages/interviewQuestion/InterviewQuestions.tsx
  frontend/src/pages/status/index.tsx
  frontend/src/pages/teams/InterviewDetail.tsx
  frontend/src/pages/teams/InterviewTeams.tsx
  frontend/src/styles/colorPalette.ts
  frontend/src/styles/sizeList.ts
  frontend/src/styles/theme.ts
  frontend/yarn.lock
Labels: 🧑🏻‍💻 프론트엔드, 🛠 리팩터링
