Repository woowacourse-teams/2022-levellog, pull requests merged in 2022-11, with the labels that each got.

#564 fix: 1.4.7 릴리즈에서 발견된 에러 수정
  .github/workflows/front-dev.yml
  .github/workflows/front-prod.yml
  .github/workflows/front-unit-test.yml
  frontend/src/components/teams/AddMember.tsx
  frontend/src/pages/interviewQuestion/InterviewQuestions.tsx
  frontend/src/pages/status/EmptyInterviewQuestion.tsx
  frontend/src/pages/teams/InterviewDetail.tsx
Labels: 🐛 버그, 🧑🏻‍💻 프론트엔드

#565 feat: 로딩 성능과 `InterviewTeams` 페이지의 웹 접근성 추가 개선
  frontend/babel.config.js
  frontend/package.json
  frontend/public/index.html
  frontend/src/assets/images/cancel.png
  frontend/src/components/header/Header.tsx
  frontend/src/components/header/Profile.tsx
  frontend/src/components/interviewQuestion/InterviewQuestionSearchForm.tsx
  frontend/src/components/teams/InterviewTeam.tsx
  frontend/yarn.lock
Labels: 🧑🏻‍💻 프론트엔드, 🛠 리팩터링

#563 feat: 에러바운더리 추가
  frontend/src/App.tsx
  frontend/src/components/@commons/ErrorBoundary.tsx
  frontend/src/components/@commons/snackbar/SnackbarContainer.tsx
  frontend/src/components/interviewQuestion/InterviewQuestion.tsx
  frontend/src/components/teams/InterviewTeam.tsx
  frontend/src/constants/constants.ts
  frontend/src/contexts/snackbarContext.tsx
  frontend/src/hooks/auth/useAuth.ts
  frontend/src/hooks/feedback/useFeedbackAdd.ts
  frontend/src/hooks/feedback/useFeedbackEdit.ts
  frontend/src/hooks/feedback/useFeedbacks.ts
  frontend/src/hooks/interviewQuestion/useInterviewQuestion.ts
  frontend/src/hooks/interviewQuestion/useInterviewQuestions.ts
  frontend/src/hooks/interviewQuestionSearch/useInterviewSearchedQuestion.ts
  frontend/src/hooks/levellog/useLevellog.ts
  frontend/src/hooks/levellog/useLevellogAdd.ts
  frontend/src/hooks/levellog/useLevellogEdit.ts
  frontend/src/hooks/levellog/useLevellogModal.ts
  frontend/src/hooks/levellog/useLevellogQuery.ts
  frontend/src/hooks/preQuestion/usePreQuestionAdd.ts
  frontend/src/hooks/preQuestion/usePreQuestionEdit.ts
  frontend/src/hooks/preQuestion/usePreQuestionModal.ts
  frontend/src/hooks/preQuestion/usePreQuestionQuery.ts
  frontend/src/hooks/team/useMember.ts
  frontend/src/hooks/team/useTeam.ts
  frontend/src/hooks/team/useTeamDetail.ts
  frontend/src/hooks/team/useTeams.ts
  frontend/src/hooks/utils/useSnackbar.ts
  frontend/src/index.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/feedback/FeedbackAdd.tsx
  frontend/src/pages/feedback/FeedbackEdit.tsx
  frontend/src/pages/feedback/Feedbacks.tsx
  frontend/src/pages/status/EmptyInterviewQuestion.tsx
  frontend/src/pages/status/Error.tsx
  frontend/src/pages/status/ErrorToHome.tsx
  frontend/src/pages/status/index.tsx
  frontend/src/pages/teams/InterviewDetail.tsx
  frontend/src/routes/Routes.tsx
  frontend/src/routes/TeamStatus.tsx
  frontend/src/utils/util.test.ts
  frontend/src/utils/util.ts
  frontend/yarn.lock
Labels: 🌟 기능, 🧑🏻‍💻 프론트엔드

#574 fix: 의도한 바와 달리 팀 상태를 보여주는 버그 수정
  frontend/src/components/teams/InterviewTeam.tsx
Labels: 🐛 버그, 🧑🏻‍💻 프론트엔드

#572 chore: 개발용 빌드 설정 수정
  .github/workflows/front-prod.yml
  frontend/.webpack/webpack.dev.js
Labels: ⚙️ 설정, 🧑🏻‍💻 프론트엔드

#576 fix: 인터뷰 질문 재검색 에러 수정
  frontend/src/hooks/interviewQuestionSearch/useInterviewSearchedQuestion.ts
  frontend/src/pages/interviewQuestion/InterviewQuestionSearch.tsx
Labels: 🐛 버그, 🧑🏻‍💻 프론트엔드

#579 release: v1.5.1
  frontend/.webpack/webpack.dev.js
  frontend/src/components/teams/InterviewTeam.tsx
  frontend/src/hooks/interviewQuestionSearch/useInterviewSearchedQuestion.ts
  frontend/src/pages/interviewQuestion/InterviewQuestionSearch.tsx
Labels: 👩🏻‍💻 백엔드, 🧑🏻‍💻 프론트엔드

#581 refactor: 코드스멜 제거
  backend/src/main/java/com/woowacourse/levellog/authentication/application/LoginService.java
  backend/src/main/java/com/woowacourse/levellog/authentication/config/AuthInterceptor.java
  backend/src/main/java/com/woowacourse/levellog/authentication/dto/response/GithubTokenResponse.java
  backend/src/main/java/com/woowacourse/levellog/common/presentation/ControllerAdvice.java
  backend/src/main/java/com/woowacourse/levellog/feedback/dto/request/FeedbackContentRequest.java
  backend/src/main/java/com/woowacourse/levellog/member/application/MemberService.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/InterviewQuestionSearchAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/MemberAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/FeedbackServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/InterviewQuestionServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/LevellogServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/MemberServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/PreQuestionServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/TeamQueryServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/TeamServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/FeedbackQueryRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/FeedbackRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/InterviewQuestionTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/LevellogTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/ParticipantTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/ParticipantsFactoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/ParticipantsTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/PreQuestionTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/RepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/TeamQueryRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/TeamTest.java
  backend/src/test/java/com/woowacourse/levellog/fixture/RestAssuredResponse.java
Labels: 👩🏻‍💻 백엔드, 🛠 리팩터링

#583 chore: frontend Prod CI 에 빈 소나큐브 빌드 job 추가
  .github/workflows/front-prod.yml
  .github/workflows/front-unit-test.yml
Labels: 🧑🏻‍💻 프론트엔드

#594 feat: 이미지 파일 캐시 버스팅이 가능하도록 content hash 추가
  frontend/.webpack/webpack.common.js
  frontend/public/index.html
  frontend/src/assets/images/favicon.ico
  frontend/src/components/feedbacks/Feedback.stories.tsx
  frontend/src/types/feedback.ts
Labels: 🧑🏻‍💻 프론트엔드

#588 fix: 비관적 잠금을 거는 쿼리에서 불필요한 JOIN 제거
  backend/src/main/java/com/woowacourse/levellog/feedback/application/FeedbackService.java
  backend/src/main/java/com/woowacourse/levellog/feedback/domain/FeedbackRepository.java
  backend/src/main/java/com/woowacourse/levellog/levellog/application/LevellogService.java
  backend/src/main/java/com/woowacourse/levellog/levellog/domain/LevellogRepository.java
  backend/src/test/java/com/woowacourse/levellog/domain/FeedbackRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/LevellogRepositoryTest.java
Labels: 🐛 버그, 👩🏻‍💻 백엔드, 🚨 빨리!

#596 fix: 비관적 락을 제거하고 유니크 제약조건을 추가한다.
  backend/src/main/java/com/woowacourse/levellog/feedback/domain/Feedback.java
  backend/src/main/java/com/woowacourse/levellog/feedback/domain/FeedbackRepository.java
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/domain/InterviewQuestionLikes.java
  backend/src/main/java/com/woowacourse/levellog/levellog/domain/Levellog.java
  backend/src/main/java/com/woowacourse/levellog/levellog/domain/LevellogRepository.java
  backend/src/main/java/com/woowacourse/levellog/member/domain/Member.java
  backend/src/main/java/com/woowacourse/levellog/member/domain/MemberRepository.java
  backend/src/main/java/com/woowacourse/levellog/prequestion/domain/PreQuestion.java
  backend/src/main/java/com/woowacourse/levellog/prequestion/domain/PreQuestionRepository.java
  backend/src/test/java/com/woowacourse/levellog/application/FeedbackServiceTest.java
Labels: 🐛 버그, 👩🏻‍💻 백엔드

#597 chore: OSIV 설정 변경
  backend/src/main/resources/application.yml
Labels: 👩🏻‍💻 백엔드, ⚙️ 설정

#598 fix: 팀 목록이 존재하지 않을 때 이미지 정렬 수정
  frontend/src/components/teams/Teams.tsx
Labels: 🐛 버그, 🧑🏻‍💻 프론트엔드, Team, 🚨 빨리!

#600 release: v1.5.3
  frontend/src/components/teams/Teams.tsx
Labels: 🐛 버그

#603 fix: 인증/인가 Asepct가 정상 동작하도록 수정
  backend/src/main/java/com/woowacourse/levellog/authentication/aspect/LoginStatusValidator.java
  backend/src/main/java/com/woowacourse/levellog/authentication/support/Verified.java
  backend/src/main/java/com/woowacourse/levellog/feedback/application/FeedbackService.java
  backend/src/main/java/com/woowacourse/levellog/interviewquestion/application/InterviewQuestionService.java
  backend/src/main/java/com/woowacourse/levellog/levellog/application/LevellogService.java
  backend/src/main/java/com/woowacourse/levellog/member/application/MemberService.java
  backend/src/main/java/com/woowacourse/levellog/prequestion/application/PreQuestionService.java
  backend/src/main/java/com/woowacourse/levellog/team/application/TeamQueryService.java
  backend/src/main/java/com/woowacourse/levellog/team/application/TeamService.java
  backend/src/test/java/com/woowacourse/levellog/application/TeamQueryServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/support/application/LoginStatusValidatorTest.java
Labels: 🐛 버그, 👩🏻‍💻 백엔드, Auth
