Repository woowacourse-teams/2022-levellog, pull requests merged in 2022-07, with the labels that each got.

#2 feat: 백엔드 초기 환경 구성
  .gitignore
  backend/levellog/.gitignore
  backend/levellog/build.gradle
  backend/levellog/gradle/wrapper/gradle-wrapper.jar
  backend/levellog/gradle/wrapper/gradle-wrapper.properties
  backend/levellog/gradlew
  backend/levellog/gradlew.bat
  backend/levellog/settings.gradle
  backend/levellog/src/main/java/com/woowacourse/levellog/LevellogApplication.java
  backend/levellog/src/main/resources/application.properties
  backend/levellog/src/test/java/com/woowacourse/levellog/LevellogApplicationTests.java
Labels: 👩🏻‍💻 백엔드, ⚙️ 설정

#6 feat: 불필요한 폴더 제거
  backend/.gitignore
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/com/woowacourse/levellog/LevellogApplication.java
  backend/src/main/resources/application.properties
  backend/src/test/java/com/woowacourse/levellog/LevellogApplicationTests.java
Labels: 👩🏻‍💻 백엔드, ⚙️ 설정

#15 chore: pr 템플릿 파일 위치 변경
  .github/pull_request_template.md
Labels: 🐛 버그, 📝 문서

#16 feat: 피드백 작성 기능 구현
  backend/build.gradle
  backend/src/main/java/com/woowacourse/levellog/LevellogApplication.java
  backend/src/main/java/com/woowacourse/levellog/application/FeedbackService.java
  backend/src/main/java/com/woowacourse/levellog/domain/Feedback.java
  backend/src/main/java/com/woowacourse/levellog/domain/FeedbackRepository.java
  backend/src/main/java/com/woowacourse/levellog/dto/FeedbackContentDto.java
  backend/src/main/java/com/woowacourse/levellog/dto/FeedbackCreateRequest.java
  backend/src/main/java/com/woowacourse/levellog/presentation/FeedbackController.java
  backend/src/main/resources/application.properties
  backend/src/main/resources/application.yml
  backend/src/test/java/com/woowacourse/levellog/LevellogApplicationTests.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/AcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/FeedbackAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/FeedbackServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/FeedbackControllerTest.java
Labels: 🌟 기능, 👩🏻‍💻 백엔드

#17 feat: 피드백 전체 조회, 삭제 기능 구현
  backend/src/main/java/com/woowacourse/levellog/application/FeedbackService.java
  backend/src/main/java/com/woowacourse/levellog/dto/FeedbackResponse.java
  backend/src/main/java/com/woowacourse/levellog/dto/FeedbacksResponse.java
  backend/src/main/java/com/woowacourse/levellog/presentation/FeedbackController.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/FeedbackAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/FeedbackServiceTest.java
Labels: 🌟 기능, 👩🏻‍💻 백엔드

#21 feat: 피드백 조회, 등록 구현
  frontend/docs/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/mockServiceWorker.js
  frontend/src/App.tsx
  frontend/src/api/feedback.ts
  frontend/src/components/@commons/Button.tsx
  frontend/src/components/@commons/Input.tsx
  frontend/src/components/@commons/SmallInput.tsx
  frontend/src/components/@commons/Style.tsx
  frontend/src/components/Feedback.tsx
  frontend/src/components/FeedbackAddButton.tsx
  frontend/src/components/LevelLogFeedback.tsx
  frontend/src/components/LevelLogReport.tsx
  frontend/src/constants/constants.ts
  frontend/src/hooks/useFeedback.ts
  frontend/src/index.tsx
  frontend/src/mocks/browser.ts
  frontend/src/mocks/handler.ts
  frontend/src/mocks/mockData.ts
  frontend/src/pages/FeedbackAdd.tsx
  frontend/src/pages/FeedbackList.tsx
  frontend/src/routes/Routes.tsx
  frontend/src/styles/GlobalStyle.ts
  frontend/src/types/index.ts
  frontend/webpack.config.js
Labels: 🌟 기능, 🧑🏻‍💻 프론트엔드

#23 [FE] 피드백 삭제하기 구현
  frontend/docs/README.md
  frontend/src/components/@commons/Button.tsx
  frontend/src/components/Feedback.tsx
  frontend/src/index.tsx
  frontend/src/mocks/handler.ts
  frontend/src/pages/FeedbackAdd.tsx
  frontend/src/pages/FeedbackList.tsx
Labels: 🌟 기능, 🧑🏻‍💻 프론트엔드

#25 docs: 최상위 디렉토리에 README 추가
  README.md
Labels: 📝 문서

#44 feat: 레벨로그 CREATE 기능 구현
  frontend/.gitignore
  frontend/docs/README.md
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/api/feedback.ts
  frontend/src/api/levellog.ts
  frontend/src/components/@commons/Button.stories.tsx
  frontend/src/components/@commons/Button.tsx
  frontend/src/components/@commons/ContentHeader.stories.tsx
  frontend/src/components/@commons/ContentHeader.tsx
  frontend/src/components/@commons/Input.stories.tsx
  frontend/src/components/@commons/Input.tsx
  frontend/src/components/@commons/Label.tsx
  frontend/src/components/@commons/SmallInput.tsx
  frontend/src/components/@commons/Style.tsx
  frontend/src/components/Feedback.tsx
  frontend/src/components/LevelLogFeedback.tsx
  frontend/src/constants/constants.ts
  frontend/src/hooks/useFeedback.ts
  frontend/src/hooks/useLevellog.ts
  frontend/src/index.tsx
  frontend/src/mocks/handler.ts
  frontend/src/mocks/mockData.ts
  frontend/src/pages/FeedbackList.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/LevellogAdd.tsx
  frontend/src/routes/Routes.tsx
  frontend/src/styles/GlobalStyle.ts
  frontend/src/types/index.ts
Labels: 🌟 기능, 🧑🏻‍💻 프론트엔드

#49 feat: Github 로그인 기능을 구현
  frontend/.gitignore
  frontend/.storybook/preview.js
  frontend/docs/secondDemo.md
  frontend/public/img/defaultProfile.png
  frontend/public/img/levellog-logo.png
  frontend/src/App.tsx
  frontend/src/api/login.ts
  frontend/src/components/@commons/Button.tsx
  frontend/src/components/Header.stories.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/ProfileDropdown.stories.tsx
  frontend/src/components/ProfileDropdown.tsx
  frontend/src/constants/constants.ts
  frontend/src/context/index.tsx
  frontend/src/hooks/useContext.ts
  frontend/src/index.tsx
  frontend/src/mocks/browser.ts
  frontend/src/mocks/handler.ts
  frontend/src/pages/Login.tsx
  frontend/src/routes/Routes.tsx
  frontend/tsconfig.json
Labels: 🌟 기능, 🧑🏻‍💻 프론트엔드

#47 feat: 레벨로그 READ 기능 구현
  frontend/docs/README.md
  frontend/src/api/levellog.ts
  frontend/src/components/@commons/Button.stories.tsx
  frontend/src/components/@commons/Button.tsx
  frontend/src/components/@commons/ContentHeader.tsx
  frontend/src/components/@commons/Input.tsx
  frontend/src/components/LevellogFeedback.tsx
  frontend/src/components/LevellogReport.tsx
  frontend/src/components/LevellogViewModal.tsx
  frontend/src/hooks/useLevellog.ts
  frontend/src/mocks/handler.ts
  frontend/src/pages/FeedbackAdd.tsx
  frontend/src/pages/FeedbackList.tsx
  frontend/src/pages/Main.tsx
  frontend/src/styles/GlobalStyle.ts
Labels: 🌟 기능, 🧑🏻‍💻 프론트엔드

#51 fix: 파일 이름 대소문자 변경
  frontend/src/components/LevelLogFeedback.tsx
  frontend/src/components/LevelLogReport.tsx
  frontend/src/hooks/useLevellog.ts
Labels: 🐛 버그

#43 feat: 레벨로그 CRUD 기능
  backend/src/main/java/com/woowacourse/levellog/application/FeedbackService.java
  backend/src/main/java/com/woowacourse/levellog/application/LevellogService.java
  backend/src/main/java/com/woowacourse/levellog/domain/Levellog.java
  backend/src/main/java/com/woowacourse/levellog/domain/LevellogRepository.java
  backend/src/main/java/com/woowacourse/levellog/dto/LevellogCreateRequest.java
  backend/src/main/java/com/woowacourse/levellog/dto/LevellogResponse.java
  backend/src/main/java/com/woowacourse/levellog/presentation/LevellogController.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/LevellogAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/LevellogServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/LevellogControllerTest.java
Labels: 🌟 기능, 👩🏻‍💻 백엔드

#45 feat: 메서드 실행 시간을 측정해서 로그를 남긴다.
  backend/.gitignore
  backend/src/main/java/com/woowacourse/levellog/aspect/LogAspect.java
  backend/src/main/java/com/woowacourse/levellog/config/LogInterceptor.java
  backend/src/main/java/com/woowacourse/levellog/config/WebConfig.java
  backend/src/main/resources/logback-spring.xml
Labels: 🌟 기능, 👩🏻‍💻 백엔드

#50 feat: 예외 처리 기능을 구현한다.
  backend/src/main/java/com/woowacourse/levellog/exception/ControllerAdvice.java
  backend/src/main/java/com/woowacourse/levellog/exception/ExceptionResponse.java
  backend/src/main/java/com/woowacourse/levellog/exception/LevellogException.java
Labels: 🌟 기능, 👩🏻‍💻 백엔드

#72 docs: Spring rest docs를 적용한다.
  backend/.gitignore
  backend/build.gradle
  backend/src/docs/asciidoc/feedback.adoc
  backend/src/docs/asciidoc/index.adoc
  backend/src/docs/asciidoc/levellog.adoc
  backend/src/test/java/com/woowacourse/levellog/acceptance/AcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/FeedbackAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/LevellogAcceptanceTest.java
Labels: 📝 문서, 👩🏻‍💻 백엔드

#52 feat: Github 로그인 기능을 구현한다.
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/com/woowacourse/levellog/application/MemberService.java
  backend/src/main/java/com/woowacourse/levellog/authentication/application/OAuthService.java
  backend/src/main/java/com/woowacourse/levellog/authentication/config/AuthenticationConfig.java
  backend/src/main/java/com/woowacourse/levellog/authentication/config/LoginMemberResolver.java
  backend/src/main/java/com/woowacourse/levellog/authentication/domain/GithubOAuthClient.java
  backend/src/main/java/com/woowacourse/levellog/authentication/domain/JwtTokenProvider.java
  backend/src/main/java/com/woowacourse/levellog/authentication/domain/OAuthClient.java
  backend/src/main/java/com/woowacourse/levellog/authentication/dto/GithubAccessTokenRequest.java
  backend/src/main/java/com/woowacourse/levellog/authentication/dto/GithubAccessTokenResponse.java
  backend/src/main/java/com/woowacourse/levellog/authentication/dto/GithubCodeRequest.java
  backend/src/main/java/com/woowacourse/levellog/authentication/dto/GithubProfileResponse.java
  backend/src/main/java/com/woowacourse/levellog/authentication/dto/LoginResponse.java
  backend/src/main/java/com/woowacourse/levellog/authentication/exception/InvalidTokenException.java
  backend/src/main/java/com/woowacourse/levellog/authentication/exception/MemberNotFoundException.java
  backend/src/main/java/com/woowacourse/levellog/authentication/presentation/LoginInterceptor.java
  backend/src/main/java/com/woowacourse/levellog/authentication/presentation/OAuthController.java
  backend/src/main/java/com/woowacourse/levellog/authentication/support/AuthorizationExtractor.java
  backend/src/main/java/com/woowacourse/levellog/authentication/support/LoginMember.java
  backend/src/main/java/com/woowacourse/levellog/config/WebConfig.java
  backend/src/main/java/com/woowacourse/levellog/domain/Member.java
  backend/src/main/java/com/woowacourse/levellog/domain/MemberRepository.java
  backend/src/main/java/com/woowacourse/levellog/dto/MemberCreateDto.java
  backend/src/main/java/com/woowacourse/levellog/dto/MemberResponse.java
  backend/src/main/java/com/woowacourse/levellog/dto/MembersResponse.java
  backend/src/main/java/com/woowacourse/levellog/presentation/MemberController.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/woowacourse/levellog/acceptance/AcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/OAuthAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/MemberServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/authentication/application/OAuthServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/authentication/domain/JwtTokenProviderTest.java
  backend/src/test/java/com/woowacourse/levellog/authentication/presentation/OAuthControllerTest.java
  backend/src/test/java/com/woowacourse/levellog/authentication/support/FakeGithubOAuthClient.java
  backend/src/test/java/com/woowacourse/levellog/authentication/support/TestAuthenticationConfig.java
  backend/src/test/java/com/woowacourse/levellog/domain/MemberRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/FeedbackControllerTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/LevellogControllerTest.java
  backend/src/test/java/com/woowacourse/levellog/support/ControllerTest.java
  backend/src/test/resources/application.yml
Labels: 🌟 기능, 👩🏻‍💻 백엔드

#75 chore: dev profile에서 로그를 파일에 기록하도록 변경한다.
  backend/src/main/resources/logback-spring.xml
Labels: 👩🏻‍💻 백엔드, ⚙️ 설정

#76 feat: Auditing을 적용한다.
  backend/src/main/java/com/woowacourse/levellog/application/FeedbackService.java
  backend/src/main/java/com/woowacourse/levellog/common/BaseEntity.java
  backend/src/main/java/com/woowacourse/levellog/config/JpaConfig.java
  backend/src/main/java/com/woowacourse/levellog/domain/Feedback.java
  backend/src/main/java/com/woowacourse/levellog/domain/FeedbackRepository.java
  backend/src/main/java/com/woowacourse/levellog/domain/Levellog.java
  backend/src/main/java/com/woowacourse/levellog/domain/Member.java
  backend/src/main/java/com/woowacourse/levellog/dto/FeedbackResponse.java
  backend/src/test/java/com/woowacourse/levellog/application/FeedbackServiceTest.java
Labels: 🌟 기능, 👩🏻‍💻 백엔드

#85 feat: 인수테스트를 위한 로그인 픽스쳐를 생성한다.
  backend/.gitignore
  backend/src/test/java/com/woowacourse/levellog/acceptance/AcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/OAuthAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/authentication/support/FakeGithubOAuthClient.java
  backend/src/test/java/com/woowacourse/levellog/authentication/support/TestAuthenticationConfig.java
  backend/src/test/java/com/woowacourse/levellog/fixture/RequestFixture.java
Labels: 🌟 기능, 👩🏻‍💻 백엔드, Auth

#86 refactor: 로그인 성공 응답에 id를 포함하도록 변경
  backend/src/main/java/com/woowacourse/levellog/authentication/application/OAuthService.java
  backend/src/main/java/com/woowacourse/levellog/authentication/dto/LoginResponse.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/AcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/MyInfoAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/OAuthAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/authentication/application/OAuthServiceTest.java
Labels: 👩🏻‍💻 백엔드, 🛠 리팩터링, Auth

#89 feat: 레벨로그 삭제 기능 구현
  frontend/.storybook/preview.js
  frontend/docs/README.md
  frontend/public/index.html
  frontend/src/ModalPortal.tsx
  frontend/src/apis/levellog.ts
  frontend/src/components/@commons/Button.stories.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/Interviewer.tsx
  frontend/src/components/LevellogViewModal.tsx
  frontend/src/components/ProfileDropdown.tsx
  frontend/src/components/RequireAuth.tsx
  frontend/src/components/feedbacks/Feedback.tsx
  frontend/src/components/feedbacks/LevellogFeedback.tsx
  frontend/src/components/feedbacks/LevellogReport.tsx
  frontend/src/components/levellogs/LevellogViewModal.stories.tsx
  frontend/src/components/levellogs/LevellogViewModal.tsx
  frontend/src/components/teams/InterviewTeam.stories.tsx
  frontend/src/components/teams/InterviewTeam.tsx
  frontend/src/components/teams/Interviewer.stories.tsx
  frontend/src/components/teams/Interviewer.tsx
  frontend/src/constants/constants.ts
  frontend/src/contexts/userContext.tsx
  frontend/src/hooks/useLevellog.ts
  frontend/src/hooks/useUser.ts
  frontend/src/index.tsx
  frontend/src/mocks/handler.ts
  frontend/src/mocks/mockData.ts
  frontend/src/pages/Home.tsx
  frontend/src/pages/Login.tsx
  frontend/src/pages/NotFound.tsx
  frontend/src/pages/feedback/FeedbackAdd.tsx
  frontend/src/pages/feedback/FeedbackList.tsx
  frontend/src/pages/levellogs/LevellogAdd.tsx
  frontend/src/pages/teams/InterviewDetail.tsx
  frontend/src/pages/teams/InterviewTeams.tsx
  frontend/src/routes/Routes.tsx
  frontend/src/types/index.ts
Labels: 🐛 버그, 🌟 기능, 🧑🏻‍💻 프론트엔드, Levellog

#90 chore: webpack 빌드 환경 분리
  frontend/.webpack/webpack.common.js
  frontend/.webpack/webpack.dev.js
  frontend/.webpack/webpack.prod.js
  frontend/package.json
Labels: ⚙️ 설정, 🧑🏻‍💻 프론트엔드

#91 feat: 팀 생성, 목록 조회, 상세 조회 구현
  backend/src/main/java/com/woowacourse/levellog/application/TeamService.java
  backend/src/main/java/com/woowacourse/levellog/domain/LevellogRepository.java
  backend/src/main/java/com/woowacourse/levellog/domain/Participant.java
  backend/src/main/java/com/woowacourse/levellog/domain/ParticipantRepository.java
  backend/src/main/java/com/woowacourse/levellog/domain/Team.java
  backend/src/main/java/com/woowacourse/levellog/dto/ParticipantIdsRequest.java
  backend/src/main/java/com/woowacourse/levellog/dto/ParticipantResponse.java
  backend/src/main/java/com/woowacourse/levellog/dto/ParticipantsResponse.java
  backend/src/main/java/com/woowacourse/levellog/dto/TeamRequest.java
  backend/src/main/java/com/woowacourse/levellog/dto/TeamResponse.java
  backend/src/main/java/com/woowacourse/levellog/dto/TeamUpdateRequest.java
  backend/src/main/java/com/woowacourse/levellog/dto/TeamsResponse.java
  backend/src/main/java/com/woowacourse/levellog/presentation/TeamController.java
  backend/src/test/java/com/woowacourse/levellog/application/TeamServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/TeamControllerTest.java
  backend/src/test/java/com/woowacourse/levellog/support/ControllerTest.java
Labels: 🌟 기능, 👩🏻‍💻 백엔드, Team

#97 feat: 레벨로그 수정기능을 구현
  frontend/docs/README.md
  frontend/src/apis/levellog.ts
  frontend/src/components/Header.tsx
  frontend/src/components/RequireAuth.tsx
  frontend/src/components/levellogs/LevellogViewModal.tsx
  frontend/src/components/teams/Interviewer.tsx
  frontend/src/constants/constants.ts
  frontend/src/hooks/useLevellog.ts
  frontend/src/mocks/handler.ts
  frontend/src/mocks/mockData.ts
  frontend/src/pages/levellogs/LevellogModify.tsx
  frontend/src/pages/teams/InterviewDetail.tsx
  frontend/src/routes/Routes.tsx
Labels: 🌟 기능, 🧑🏻‍💻 프론트엔드

#96 chore: Github Action CI 스크립트 추가
  .github/workflows/main.yml
Labels: 👩🏻‍💻 백엔드, ⚙️ 설정, 인프라

#92 feat: 멤버 닉네임 검색 기능 구현
  backend/src/main/java/com/woowacourse/levellog/application/MemberService.java
  backend/src/main/java/com/woowacourse/levellog/domain/MemberRepository.java
  backend/src/main/java/com/woowacourse/levellog/presentation/MemberController.java
  backend/src/test/java/com/woowacourse/levellog/application/MemberServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/MemberRepositoryTest.java
Labels: 🌟 기능, 👩🏻‍💻 백엔드, Member

#93 test: 비활성화 되어있는 테스트를 구현한다.
  backend/src/docs/asciidoc/auth.adoc
  backend/src/docs/asciidoc/index.adoc
  backend/src/test/java/com/woowacourse/levellog/acceptance/AcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/FeedbackAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/LevellogAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/MyInfoAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/OAuthAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/fixture/RequestFixture.java
  backend/src/test/java/com/woowacourse/levellog/presentation/FeedbackControllerTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/LevellogControllerTest.java
Labels: 👩🏻‍💻 백엔드, Levellog, Feedback, 📚 테스트

#98 feat: 팀 수정, 삭제 기능 구현
  backend/src/docs/asciidoc/index.adoc
  backend/src/docs/asciidoc/team.adoc
  backend/src/main/java/com/woowacourse/levellog/application/TeamService.java
  backend/src/main/java/com/woowacourse/levellog/domain/LevellogRepository.java
  backend/src/main/java/com/woowacourse/levellog/domain/ParticipantRepository.java
  backend/src/main/java/com/woowacourse/levellog/domain/Team.java
  backend/src/main/java/com/woowacourse/levellog/dto/ParticipantIdsRequest.java
  backend/src/main/java/com/woowacourse/levellog/dto/ParticipantsResponse.java
  backend/src/main/java/com/woowacourse/levellog/dto/TeamResponse.java
  backend/src/main/java/com/woowacourse/levellog/exception/HostUnauthorizedException.java
  backend/src/main/java/com/woowacourse/levellog/presentation/TeamController.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/TeamAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/TeamServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/TeamControllerTest.java
Labels: 🌟 기능, 👩🏻‍💻 백엔드, Team

#103 feat: 피드백 수정 기능 및 UI 수정
  frontend/.gitignore
  frontend/.webpack/webpack.dev.js
  frontend/package.json
  frontend/public/mockServiceWorker.js
  frontend/src/App.tsx
  frontend/src/apis/feedback.ts
  frontend/src/components/@commons/Button.tsx
  frontend/src/components/@commons/ContentHeader.tsx
  frontend/src/components/@commons/Input.tsx
  frontend/src/components/@commons/Style.tsx
  frontend/src/components/Footer.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/ProfileDropdown.tsx
  frontend/src/components/feedbacks/Feedback.tsx
  frontend/src/components/feedbacks/LevellogFeedback.tsx
  frontend/src/components/feedbacks/LevellogReport.tsx
  frontend/src/components/levellogs/LevellogViewModal.tsx
  frontend/src/components/teams/InterviewTeam.tsx
  frontend/src/components/teams/Interviewer.tsx
  frontend/src/constants/constants.ts
  frontend/src/hooks/useFeedback.ts
  frontend/src/index.tsx
  frontend/src/mocks/handler.ts
  frontend/src/mocks/mockData.ts
  frontend/src/pages/feedback/FeedbackAdd.tsx
  frontend/src/pages/feedback/FeedbackList.tsx
  frontend/src/pages/levellogs/LevellogAdd.tsx
  frontend/src/pages/teams/InterviewDetail.tsx
  frontend/src/pages/teams/InterviewTeams.tsx
  frontend/src/routes/Routes.tsx
  frontend/src/styles/GlobalStyle.ts
  frontend/src/styles/colorPalette.ts
  frontend/src/types/index.ts
Labels: 🌟 기능, 🧑🏻‍💻 프론트엔드

#105 hotfix: login redirect uri 수정
  frontend/src/components/Header.tsx
Labels: 🧑🏻‍💻 프론트엔드

#102 feat: 인터셉터에 커스텀 어노테이션 적용
  backend/src/main/java/com/woowacourse/levellog/authentication/config/AuthenticationConfig.java
  backend/src/main/java/com/woowacourse/levellog/authentication/config/NoAuthentication.java
  backend/src/main/java/com/woowacourse/levellog/authentication/presentation/LoginInterceptor.java
  backend/src/main/java/com/woowacourse/levellog/authentication/presentation/OAuthController.java
  backend/src/main/java/com/woowacourse/levellog/presentation/LevellogController.java
  backend/src/main/java/com/woowacourse/levellog/presentation/TeamController.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/LevellogAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/LevellogControllerTest.java
Labels: 👩🏻‍💻 백엔드, Auth

#108 fix: 팀에 레벨로그가 이미 존재할 때 레벨로그를 작성하면 예외를 던진다.
  backend/src/main/java/com/woowacourse/levellog/application/LevellogService.java
  backend/src/main/java/com/woowacourse/levellog/exception/LevellogAlreadyExistException.java
  backend/src/test/java/com/woowacourse/levellog/application/LevellogServiceTest.java
Labels: 🐛 버그, 👩🏻‍💻 백엔드, Levellog

#109 fix: 피드백 생성 기능 버그 수정
  backend/src/main/java/com/woowacourse/levellog/application/FeedbackService.java
  backend/src/main/java/com/woowacourse/levellog/domain/FeedbackRepository.java
  backend/src/main/java/com/woowacourse/levellog/exception/FeedbackAlreadyExistException.java
  backend/src/main/java/com/woowacourse/levellog/exception/InvalidFeedbackException.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/AcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/FeedbackAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/FeedbackServiceTest.java
Labels: 🐛 버그, 👩🏻‍💻 백엔드, Feedback

#110 fix: 피드백의 작성자 이거나 수신자만 삭제할 수 있는 기능
  backend/src/main/java/com/woowacourse/levellog/application/FeedbackService.java
  backend/src/main/java/com/woowacourse/levellog/domain/Feedback.java
  backend/src/main/java/com/woowacourse/levellog/presentation/FeedbackController.java
  backend/src/test/java/com/woowacourse/levellog/application/FeedbackServiceTest.java
Labels: 🐛 버그, 👩🏻‍💻 백엔드, Feedback

#113 feat: 팀에 속하지 않는 멤버가 피드백을 작성하려는 경우 예외 발생 기능
  backend/src/main/java/com/woowacourse/levellog/application/FeedbackService.java
  backend/src/main/java/com/woowacourse/levellog/domain/ParticipantRepository.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/FeedbackAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/FeedbackServiceTest.java
Labels: 👩🏻‍💻 백엔드

#121 refactor: 픽스처를 사용해서 인수 테스트 리팩토링
  backend/src/test/java/com/woowacourse/levellog/acceptance/AcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/FeedbackAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/LevellogAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/MyInfoAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/TeamAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/fixture/RestAssuredResponse.java
  backend/src/test/java/com/woowacourse/levellog/fixture/RestAssuredTemplate.java
Labels: 👩🏻‍💻 백엔드, 🛠 리팩터링, 📚 테스트

#133 refactor: 멤버 도메인 리팩토링
  backend/src/main/java/com/woowacourse/levellog/authentication/application/OAuthService.java
  backend/src/main/java/com/woowacourse/levellog/authentication/domain/GithubOAuthClient.java
  backend/src/main/java/com/woowacourse/levellog/authentication/domain/OAuthClient.java
  backend/src/main/java/com/woowacourse/levellog/authentication/dto/GithubProfileDto.java
  backend/src/main/java/com/woowacourse/levellog/common/exception/InvalidFieldException.java
  backend/src/main/java/com/woowacourse/levellog/common/exception/LevellogException.java
  backend/src/main/java/com/woowacourse/levellog/feedback/application/FeedbackService.java
  backend/src/main/java/com/woowacourse/levellog/feedback/dto/FeedbackResponse.java
  backend/src/main/java/com/woowacourse/levellog/member/application/MemberService.java
  backend/src/main/java/com/woowacourse/levellog/member/domain/Member.java
  backend/src/main/java/com/woowacourse/levellog/member/domain/MemberRepository.java
  backend/src/main/java/com/woowacourse/levellog/member/dto/MemberDto.java
  backend/src/main/java/com/woowacourse/levellog/member/dto/MembersDto.java
  backend/src/main/java/com/woowacourse/levellog/member/exception/InvalidFieldException.java
  backend/src/main/java/com/woowacourse/levellog/member/presentation/MemberController.java
  backend/src/main/java/com/woowacourse/levellog/member/presentation/MyInfoController.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/AcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/OAuthAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/FeedbackServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/MemberServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/OAuthServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/config/FakeGithubOAuthClient.java
  backend/src/test/java/com/woowacourse/levellog/domain/MemberTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/MyInfoControllerTest.java
Labels: 👩🏻‍💻 백엔드, 🛠 리팩터링, Member

#134 fix: 백엔드 CI 스크립트 수정
  .github/workflows/main.yml
Labels: 🐛 버그, 👩🏻‍💻 백엔드, ⚙️ 설정, 인프라

#138 chore: mockMvc에 Rest Docs 설정 추가
  backend/build.gradle
  backend/src/test/java/com/woowacourse/levellog/presentation/ControllerTest.java
Labels: 📝 문서, 👩🏻‍💻 백엔드, ⚙️ 설정

#140 refactor: 스프린트1,2에서 에러가 날만한 코드 수정
  .github/workflows/release-drafter.yml
  frontend/src/apis/feedback.ts
  frontend/src/apis/levellog.ts
  frontend/src/apis/login.ts
  frontend/src/apis/teams.ts
  frontend/src/components/@commons/Button.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/ProfileDropdown.stories.tsx
  frontend/src/components/ProfileDropdown.tsx
  frontend/src/components/RequireAuth.tsx
  frontend/src/components/feedbacks/Feedback.tsx
  frontend/src/components/levellogs/LevellogForm.tsx
  frontend/src/components/levellogs/LevellogViewModal.tsx
  frontend/src/components/teams/Interviewer.tsx
  frontend/src/constants/constants.ts
  frontend/src/hooks/useAuth.ts
  frontend/src/hooks/useFeedback.ts
  frontend/src/hooks/useLevellog.ts
  frontend/src/hooks/useLevellogModal.ts
  frontend/src/hooks/useTeams.ts
  frontend/src/hooks/useUser.ts
  frontend/src/index.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/Login.tsx
  frontend/src/pages/feedback/FeedbackAdd.tsx
  frontend/src/pages/feedback/FeedbackList.tsx
  frontend/src/pages/levellogs/LevellogAdd.tsx
  frontend/src/pages/levellogs/LevellogEdit.tsx
  frontend/src/pages/levellogs/LevellogModify.tsx
  frontend/src/pages/teams/InterviewDetail.tsx
  frontend/src/pages/teams/InterviewTeams.tsx
  frontend/src/routes/Auth.tsx
  frontend/src/routes/Routes.tsx
  frontend/src/styles/colorPalette.ts
Labels: 🐛 버그, 🧑🏻‍💻 프론트엔드, 🛠 리팩터링, Levellog, Feedback, Team, Auth

#146 fix: 피드백 삭제, 작성이 되지 않는 버그 수정
  frontend/src/components/feedbacks/Feedback.tsx
  frontend/src/hooks/useFeedback.ts
  frontend/src/pages/feedback/FeedbackList.tsx
Labels: 🐛 버그, 🧑🏻‍💻 프론트엔드

#151 chore: 배포 환경 분리
  frontend/.webpack/webpack.common.js
  frontend/.webpack/webpack.dev.js
  frontend/.webpack/webpack.js
  frontend/.webpack/webpack.prod.js
  frontend/package.json
  frontend/src/apis/feedback.ts
  frontend/src/apis/levellog.ts
  frontend/src/apis/login.ts
  frontend/src/apis/teams.ts
  frontend/src/constants/constants.ts
  frontend/src/hooks/useUser.ts
  frontend/src/index.tsx
Labels: ⚙️ 설정, 🧑🏻‍💻 프론트엔드

#147 refactor: Auth 도메인 리팩토링
  backend/src/docs/asciidoc/auth.adoc
  backend/src/main/java/com/woowacourse/levellog/authentication/application/OAuthService.java
  backend/src/main/java/com/woowacourse/levellog/authentication/config/AuthInterceptor.java
  backend/src/main/java/com/woowacourse/levellog/authentication/config/LoginMemberResolver.java
  backend/src/main/java/com/woowacourse/levellog/authentication/domain/GithubOAuthClient.java
  backend/src/main/java/com/woowacourse/levellog/authentication/domain/OAuthClient.java
  backend/src/main/java/com/woowacourse/levellog/authentication/dto/GithubAccessTokenDto.java
  backend/src/main/java/com/woowacourse/levellog/authentication/dto/GithubCodeDto.java
  backend/src/main/java/com/woowacourse/levellog/authentication/dto/GithubProfileDto.java
  backend/src/main/java/com/woowacourse/levellog/authentication/dto/GithubTokenDto.java
  backend/src/main/java/com/woowacourse/levellog/authentication/dto/LoginDto.java
  backend/src/main/java/com/woowacourse/levellog/authentication/exception/InvalidTokenException.java
  backend/src/main/java/com/woowacourse/levellog/authentication/presentation/OAuthController.java
  backend/src/main/java/com/woowacourse/levellog/authentication/support/Authentic.java
  backend/src/main/java/com/woowacourse/levellog/authentication/support/JwtTokenProvider.java
  backend/src/main/java/com/woowacourse/levellog/authentication/support/PublicAPI.java
  backend/src/main/java/com/woowacourse/levellog/common/exception/LevellogException.java
  backend/src/main/java/com/woowacourse/levellog/common/presentation/ControllerAdvice.java
  backend/src/main/java/com/woowacourse/levellog/feedback/presentation/FeedbackController.java
  backend/src/main/java/com/woowacourse/levellog/levellog/presentation/LevellogController.java
  backend/src/main/java/com/woowacourse/levellog/member/presentation/MyInfoController.java
  backend/src/main/java/com/woowacourse/levellog/team/presentation/TeamController.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/AcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/LevellogAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/OAuthAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/FeedbackServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/LevellogServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/MemberServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/OAuthServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/ServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/TeamServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/config/FakeGithubOAuthClient.java
  backend/src/test/java/com/woowacourse/levellog/fixture/RestAssuredResponse.java
  backend/src/test/java/com/woowacourse/levellog/presentation/ControllerTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/OAuthControllerTest.java
Labels: 📝 문서, 👩🏻‍💻 백엔드, 🛠 리팩터링, Auth

#148 refactor: Member 도메인 리팩토링
  backend/src/docs/asciidoc/index.adoc
  backend/src/docs/asciidoc/member.adoc
  backend/src/docs/asciidoc/myinfo.adoc
  backend/src/main/java/com/woowacourse/levellog/common/exception/InvalidFieldException.java
  backend/src/main/java/com/woowacourse/levellog/feedback/application/FeedbackService.java
  backend/src/main/java/com/woowacourse/levellog/levellog/application/LevellogService.java
  backend/src/main/java/com/woowacourse/levellog/member/application/MemberService.java
  backend/src/main/java/com/woowacourse/levellog/member/domain/Member.java
  backend/src/main/java/com/woowacourse/levellog/member/dto/MemberCreateDto.java
  backend/src/main/java/com/woowacourse/levellog/member/dto/MemberDto.java
  backend/src/main/java/com/woowacourse/levellog/member/dto/MembersDto.java
  backend/src/main/java/com/woowacourse/levellog/member/dto/NicknameUpdateDto.java
  backend/src/main/java/com/woowacourse/levellog/member/exception/MemberAlreadyExistException.java
  backend/src/main/java/com/woowacourse/levellog/member/exception/MemberNotFoundException.java
  backend/src/main/java/com/woowacourse/levellog/member/presentation/MemberController.java
  backend/src/main/java/com/woowacourse/levellog/member/presentation/MyInfoController.java
  backend/src/main/java/com/woowacourse/levellog/team/application/TeamService.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/MemberAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/MyInfoAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/MemberServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/MemberTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/MyInfoControllerTest.java
Labels: 👩🏻‍💻 백엔드, 🛠 리팩터링, Member, MyInfo

#139 refactor: 피드백 관련 코드 리팩토링
  backend/src/docs/asciidoc/feedback.adoc
  backend/src/main/java/com/woowacourse/levellog/feedback/application/FeedbackService.java
  backend/src/main/java/com/woowacourse/levellog/feedback/domain/Feedback.java
  backend/src/main/java/com/woowacourse/levellog/feedback/domain/FeedbackRepository.java
  backend/src/main/java/com/woowacourse/levellog/feedback/dto/FeedbackContentDto.java
  backend/src/main/java/com/woowacourse/levellog/feedback/dto/FeedbackDto.java
  backend/src/main/java/com/woowacourse/levellog/feedback/dto/FeedbackResponse.java
  backend/src/main/java/com/woowacourse/levellog/feedback/dto/FeedbackWriteDto.java
  backend/src/main/java/com/woowacourse/levellog/feedback/dto/FeedbacksDto.java
  backend/src/main/java/com/woowacourse/levellog/feedback/exception/FeedbackAlreadyExistException.java
  backend/src/main/java/com/woowacourse/levellog/feedback/exception/FeedbackNotFoundException.java
  backend/src/main/java/com/woowacourse/levellog/feedback/exception/InvalidFeedbackException.java
  backend/src/main/java/com/woowacourse/levellog/feedback/presentation/FeedbackController.java
  backend/src/main/java/com/woowacourse/levellog/levellog/domain/Levellog.java
  backend/src/main/java/com/woowacourse/levellog/member/presentation/MyInfoController.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/FeedbackAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/MyInfoAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/FeedbackServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/FeedbackRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/FeedbackTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/FeedbackControllerTest.java
Labels: 📝 문서, 👩🏻‍💻 백엔드, 🛠 리팩터링, Feedback

#149 refactor: Levellog 도메인 리팩토링
  backend/src/docs/asciidoc/levellog.adoc
  backend/src/main/java/com/woowacourse/levellog/authentication/dto/GithubTokenDto.java
  backend/src/main/java/com/woowacourse/levellog/common/exception/UnauthorizedException.java
  backend/src/main/java/com/woowacourse/levellog/feedback/domain/Feedback.java
  backend/src/main/java/com/woowacourse/levellog/levellog/application/LevellogService.java
  backend/src/main/java/com/woowacourse/levellog/levellog/domain/Levellog.java
  backend/src/main/java/com/woowacourse/levellog/levellog/domain/LevellogRepository.java
  backend/src/main/java/com/woowacourse/levellog/levellog/dto/LevellogDto.java
  backend/src/main/java/com/woowacourse/levellog/levellog/dto/LevellogRequest.java
  backend/src/main/java/com/woowacourse/levellog/levellog/dto/LevellogResponse.java
  backend/src/main/java/com/woowacourse/levellog/levellog/exception/LevellogAlreadyExistException.java
  backend/src/main/java/com/woowacourse/levellog/levellog/exception/LevellogNotFoundException.java
  backend/src/main/java/com/woowacourse/levellog/levellog/exception/UnauthorizedException.java
  backend/src/main/java/com/woowacourse/levellog/levellog/presentation/LevellogController.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/AcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/FeedbackAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/LevellogAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/MyInfoAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/TeamAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/FeedbackServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/LevellogServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/MemberServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/FeedbackRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/FeedbackTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/LevellogRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/LevellogTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/FeedbackControllerTest.java
  backend/src/test/java/com/woowacourse/levellog/presentation/LevellogControllerTest.java
Labels: 📝 문서, 👩🏻‍💻 백엔드, 🛠 리팩터링, Levellog

#150 refactor: Team 도메인 리팩토링
  backend/src/docs/asciidoc/team.adoc
  backend/src/main/java/com/woowacourse/levellog/levellog/application/LevellogService.java
  backend/src/main/java/com/woowacourse/levellog/team/application/TeamService.java
  backend/src/main/java/com/woowacourse/levellog/team/domain/Team.java
  backend/src/main/java/com/woowacourse/levellog/team/dto/ParticipantDto.java
  backend/src/main/java/com/woowacourse/levellog/team/dto/ParticipantIdsDto.java
  backend/src/main/java/com/woowacourse/levellog/team/dto/ParticipantIdsRequest.java
  backend/src/main/java/com/woowacourse/levellog/team/dto/TeamCreateDto.java
  backend/src/main/java/com/woowacourse/levellog/team/dto/TeamDto.java
  backend/src/main/java/com/woowacourse/levellog/team/dto/TeamResponse.java
  backend/src/main/java/com/woowacourse/levellog/team/dto/TeamUpdateDto.java
  backend/src/main/java/com/woowacourse/levellog/team/dto/TeamsDto.java
  backend/src/main/java/com/woowacourse/levellog/team/exception/HostUnauthorizedException.java
  backend/src/main/java/com/woowacourse/levellog/team/exception/TeamNotFoundException.java
  backend/src/main/java/com/woowacourse/levellog/team/presentation/TeamController.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/AcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/LevellogAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/acceptance/TeamAcceptanceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/FeedbackServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/LevellogServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/OAuthServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/application/TeamServiceTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/FeedbackRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/FeedbackTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/LevellogTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/ParticipantRepositoryTest.java
  backend/src/test/java/com/woowacourse/levellog/domain/TeamTest.java
  backend/src/test/java/com/woowacourse/levellog/fixture/RestAssuredResponse.java
  backend/src/test/java/com/woowacourse/levellog/presentation/TeamControllerTest.java
Labels: 📝 문서, 👩🏻‍💻 백엔드, 🛠 리팩터링, Team
